### ISSUE TITLE
Debian: depends on non-headless jre

### ISSUE THREAD

**Issue by jmkgreen** [jmxtrans/jmxtrans#173]
Here's a box I'm planning to install jmxtrans to for playground purposes:

jamesg@elasticsearch:~$ dpkg -l |grep jdk
ii  openjdk-7-jre-headless:amd64     7u65-2.5.2-3~14.04            amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
jamesg@elasticsearch:~$ dpkg -l |grep jre
ii  default-jre-headless             2:1.7-51                      amd64        Standard Java or Java compatible Runtime (headless)
ii  icedtea-7-jre-jamvm:amd64        7u65-2.5.2-3~14.04            amd64        Alternative JVM for OpenJDK, using JamVM
ii  openjdk-7-jre-headless:amd64     7u65-2.5.2-3~14.04            amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

Trouble is:

jamesg@elasticsearch:~$ sudo dpkg -i jmxtrans_20121016-175251-ab6cfd36e3-1_all.deb
(Reading database ... 246731 files and directories currently installed.)
Preparing to unpack jmxtrans_20121016-175251-ab6cfd36e3-1_all.deb ...
Unpacking jmxtrans (20121016-175251-ab6cfd36e3-1) over (20121016-175251-ab6cfd36e3-1) ...
dpkg: dependency problems prevent configuration of jmxtrans:
 jmxtrans depends on java2-runtime; however:
  Package java2-runtime is not installed.

dpkg: error processing package jmxtrans (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 jmxtrans

jamesg@elasticsearch:~$ sudo apt-get install -s java2-runtime
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package java2-runtime is a virtual package provided by:
  openjdk-6-jre 6b32-1.13.4-4ubuntu0.14.04.1
  openjdk-7-jre 7u65-2.5.2-3~14.04
  gcj-jre 4:4.8.2-1ubuntu6
  gcj-4.8-jre 4.8.2-19ubuntu1
  default-jre 2:1.7-51
You should explicitly select one to install.

jamesg@elasticsearch:~$ sudo apt-get -sf install openjdk-7-jre
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 openjdk-7-jre : Depends: libgif4 (>= 4.1.4) but it is not going to be installed
                 Depends: libgtk2.0-0 (>= 2.8.0) but it is not going to be installed
                 Depends: libpulse0 (>= 1:0.99.1) but it is not going to be installed
                 Depends: libgl1-mesa-glx but it is not going to be installed or
                          libgl1
                 Depends: libatk-wrapper-java-jni (>= 0.30.4-0ubuntu2) but it is not going to be installed
                 Recommends: libgnome2-0 but it is not going to be installed
                 Recommends: libgnomevfs2-0 but it is not going to be installed
                 Recommends: libgconf2-4 but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

So it seems the .deb is reliant on a distribution of java that installs graphical components. Currently I'm going to have to pull apart this box and re-install everything to get jmxtrans to install which is not palatable.

**Comment by praste** [comment]
How do you build debian package? I don't see any profile that would do it.

**Comment by praste** [comment]
How do you build a debian package (using maven). I don't see a profile for that.

**Comment by gehel** [comment]
There is no profile yet to build DEB files with Maven. And the ant build is non working at the moment. It was hard to make it follow the changes in Maven build. If you are motivated, introducing a way to build DEB with Maven would make a lot of good !

**Comment by jmkgreen** [comment]
https://github.com/jordansissel/fpm is the modern swiss army knife in this
territory I believe. I build ActiveMQ debs using this quite easily.

**Comment by gehel** [comment]
Yep, we've had some discussionaround FPM in #166

**Comment by praste** [comment]
I have used jdeb-maven-plugin to build packages in the past. Let's see if I
can use that

**Comment by lookfirst** [comment]
The difficult part isn't the tool to build the deb/rpm, it is correctly getting all the init scripts, log files and permissions for all the files in the package to work.

**Comment by praste** [comment]
I will look at last deb package built (we which is available for download)
and try to work things

**Comment by gehel** [comment]
Should be fixed by #303. Please reopen if you find any issue.
