### ISSUE TITLE
Start using project Lombok

### ISSUE THREAD

**Issue by gehel** [jmxtrans/jmxtrans#187]
As discussed in [this comment](https://github.com/jmxtrans/jmxtrans/commit/d8b274f5aa5d828cd90f254f08421dd59c36d5f5#commitcomment-8125947), it might make sense to use [project Lombok](http://projectlombok.org/) to remove some of the boilerplate code.

**Comment by shuklaalok7** [comment]
I +1 the use of project Lombok. I use it in my every java project (public or not), it's really handy.

**Comment by gehel** [comment]
I have to admit that I dont like Lombok all that much. I'm open minded and if someone sends a PR with a good implementation, I'm ready to review and accept it. And there's a good chance that @lookfirst will accept it anyway.

My conditions for acceptance would be:

* clear value added
* out of the box integration with Intellij and Eclipse

**Comment by lookfirst** [comment]
Agreed on the criteria. Lombok kicks ass though.

Jon

**Comment by cyrille-leclerc** [comment]
@gehel do you mean introduce Lombok in jmxtrans2?

I must admit that I am not a fan of this sorcery but the Lombok project is very mature and still very active so if there is a good integration in IntelliJ, I'm ok for it.

Cyrille

**Comment by gehel** [comment]
@cyrille-leclerc no, I mean JmxTrans 1 (standalone). That was a proposal from @lookfirst. I'm not against introducing Lombok in JmxTrans 2, but as I said before, I'm not a big fan of it. I'd rather put my efforts in removing all getters and setters ... My feeling is that Lombok simplify things that are fairly ugly in Java and encourage dubious design. There are a few Lombok annotations that might bring value to pre-Java 7 projects, but now that we have `try-with-resources` and `java.lang.Objects`, I do not see much reason to use it.
