### ISSUE TITLE
Host array

### ISSUE THREAD

**Issue by allertec** [jmxtrans/jmxtrans#214]
Hi,

is there any way to define array of hosts in JSON query file instead putting each server one below each other? I tried to use following convention:
host : [host1, host2]

but unfortunately it doesn`t wotk.

Thank you

**Comment by lookfirst** [comment]
Nope. The idea with the json is that it is a format that is great for auto generation.

This is an issue tracker, not a forum, so please ask future questions on the mailing lists or gitter. I'm going to close this.
