### ISSUE TITLE
LibratoWriter includes descriptive User-Agent

### ISSUE THREAD

**Issue by mheffner** [jmxtrans/jmxtrans#216]
I'm from the Librato team. It would help us to include a descriptive User-Agent header in the LibratoWriter that includes "jmxtrans" and the version number of jmxtrans, eg. "jmxtrans/1.2.3". This would assist in our debugging when working with users that are sending data with jmxtrans to Librato.

We have a full write-up here: http://support.metrics.librato.com/knowledgebase/articles/175825-how-to-set-a-custom-user-agent-when-integrating-wi

**Comment by gehel** [comment]
That would definitely be a welcomed contribution ! I'll promise to port it fast to JmxTrans 2 ... (but let me keep "fast" loosely defined).
