### ISSUE TITLE
logging is not working as expected

### ISSUE THREAD

**Issue by praste** [jmxtrans/jmxtrans#221]
I am not sure why are we redirecting process output to the log file in 'start()' function inside 'jmxtrans.sh' script.

I see output always going to stdout (even when I commented it out). If I am using StdoutWriter, I would like to separate jmxtrans logs from query results

**Comment by gehel** [comment]
StdoutWriter is probably not the best OutputWriter for a production setup. It is quite useful for testing purpose. I suggest you have a look at the [Log4JWriter](https://github.com/jmxtrans/jmxtrans/blob/master/src/com/googlecode/jmxtrans/model/output/Log4JWriter.java) to route metrics to a specific file. We might want to implement a dedicated FileOutputWriter ...

While JmxTrans logs should go to a file (you can tune logging configuration for your specific needs) there are some cases where you will still get garbage on stdout (the first being error in the setup of the logging framework).

Does that make sense for you ?

**Comment by praste** [comment]
I am using StdoutWriter for testing only. What I am wondering about is if
log file is already specified in log4j.xml then why is there a need to
redirect output of java process. If I remove the redirect I don't see
output being written to the file specified in log4j. Also, changing
LOG_LEVEL to info etc has no effect.


On Tue, Feb 3, 2015 at 5:26 PM, Guillaume Lederrey <notifications@github.com

**Comment by gehel** [comment]
Redirecting output when starting a service is a good practice. If you dont and there is some output (which will happen in some error cases) you'll loose that output.

Note that there might well be some problems in the current log4j configuration. #215 has been opened about similar problems. Some cleanup is required ...

If you have some free time, a pull request is always welcomed !

**Comment by praste** [comment]
I did some digging and looks like as we have added logback to our dependencies, it now expects logback.xml instead of log4j.xml (I am not sure if there is a way to make log4j.xml to work with current library dependencies).

Even if it is possible to do so, we should either 'add classpath attribute to the manifest and explicitly add log4j.xml to the classpath or move log4j.xml outside the jar and add -Dlog4j.configuration=<path_to_log4j.xml> to VM arguments.

I will submit a patch for logback, however, I think most of us would hate to move to logback

**Comment by gehel** [comment]
As discussed in #215, the preferred solution would be to move everything we can to slf4j and make the choice of logback vs log4j as late as possible. But just having a correctly working logging system, whatever the solution, is of course a good first step anyway.

**Comment by stevenbower** [comment]
Agree the slf4j aproach with log4j as the target I this most robust approach and is what is used in many other large open source tools

**Comment by praste** [comment]
@stevenbower 
I looked through the details and found logback and work with slf4j just fine. More details available at http://logback.qos.ch/reasonsToSwitch.html

**Comment by gehel** [comment]
SLF4J work well both with logback and with log4j (they are all written by Ceki Gülcü so that's not much of a surprise). As our users are used to configure log4j.xml for jmxtrans logging, it make sense to use SLF4J with a log4j runtime. using SLF4J for internal logging will allow to switch easily to another backend at some point if we need to. Ceki has been pushing to deprecate log4j for quite some time ... but we're probably not ready to do that for this project.

**Comment by stevenbower** [comment]
Also will allow jmxtrans to be more easily embedded in other software

**Comment by gehel** [comment]
In term of embedding, that's the role of [embedded-jmxtrans](https://github.com/jmxtrans/embedded-jmxtrans), [jmxtrans-agent](https://github.com/jmxtrans/embedded-jmxtrans) and [jmxtrans2](https://github.com/jmxtrans/jmxtrans2). And there, the approach is even more radical : no dependency on any logging framework. Not even [java.util.logging](http://docs.oracle.com/javase/7/docs/api/java/util/logging/package-summary.html).

**Comment by praste** [comment]
can this be closed now that logging is fixed

**Comment by lookfirst** [comment]
Thanks!
