### ISSUE TITLE
JSON attribute for non-ssl connetions

### ISSUE THREAD

**Issue by dpmitchell** [jmxtrans/jmxtrans#222]
Hey,

We've been using jmxtrans and love it! But I'm currently running into connection refused problems. I can telnet to the correct port and it's open. My thinking right now is that it's trying to use a secure connection.

Is there an option to connect insecurely? 

We're running a Java applicaiton with Java 8 (perhaps this has something to do with it)

Thanks,
Dan

**Comment by gehel** [comment]
This sound like a question for the [Google group](https://groups.google.com/forum/#!forum/jmxtrans) more than an actual issue. That being said:

Do you have the exact error message ? An extract of the configuration of your failing connection ?

**Comment by lookfirst** [comment]
What @gehel said. I'm going to close this issue.

**Comment by dpmitchell** [comment]
Sorry guys, yes I do have the actual error, I posted it to the google group. Having one of those days :)
