### ISSUE TITLE
Output writer settings should accept environment variables 

### ISSUE THREAD

**Issue by magro** [jmxtrans/jmxtrans#233]
I'd like to embed jmxtrans in my application (querying the local mbean server) and use an environment variable / system property to define the output writer (statsd host). This is useful when the application is deployed in different environments (e.g. dev/integration/prod).

AFAICS it's not yet possible to specify an environment variable / system property to use for  the output settings.

**Comment by gehel** [comment]
You should probably have a look at [embedded-jmxtrans](https://github.com/jmxtrans/embedded-jmxtrans). While the environment variable based configuration does not exist at this point, it should be fairly easy to add it.

**Comment by cyrille-leclerc** [comment]
Hell @magro 

Both [embedded-jmxtrans](https://github.com/jmxtrans/embedded-jmxtrans) and [jmxtrans-agent](https://github.com/jmxtrans/jmxtrans-agent) seem to fit with your need (the former embedded at the app level, the later embedded at the jvm level) and support system & environment variables with a syntax like `${graphite.host:2003}`.

**Comment by magro** [comment]
Guillaume, Cyrille, thanks for your answers, embedded-jmxtrans looks like a perfect match. Originally I wanted to push data to statsd, but pushing to graphite directly should also be fine. I'm also watching jmxtrans2, sounds like a great next step!

**Comment by gehel** [comment]
Help welcomed on JmxTrans 2 if you have some spare time ... ;-)

**Comment by magro** [comment]
Yeah, I wish I had more time and could help a bit, but I've still some things to do in other projects, sorry.
