### ISSUE TITLE
RPM Installation Issues

### ISSUE THREAD

**Issue by bijugs** [jmxtrans/jmxtrans#278]
Tried to install version [249](http://central.maven.org/maven2/org/jmxtrans/jmxtrans/249/) rpm on a CentOS VM. 

- According to [installation document](https://github.com/jmxtrans/jmxtrans/wiki/Installation#installing-the-rpm) the ``jmxtrans`` init.d script should be available under ``/etc/init.d`` and it seems to be missing after the install. Instead there is a ``jmxtransd`` script available. 
- Also the installation fails if the user ``jmxtrans`` is already on the system which is not the case with the ``debian`` package. If the user is already existing can we skip the user creation logic instead of failing the installation process?

**Comment by gehel** [comment]
This seems to be 2 separate issues. I'll fix the daemon name right now, new snapshot should be available by tomorrow. I want to run some more tests for the user creation (if you want to send a PR for this one, I'll be happy to accept it. my bash-fo is rusty ...)

**Comment by hgomez** [comment]
I worked on initial rpm but things changed over the years.
I could review specfile PR :)

**Comment by hgomez** [comment]
About jmxtrans user already existing, it shouldn't
user is create in %pre and removed in %postun
By not creating jmxtrans user, we may have different uid than expected by rpm

**Comment by gehel** [comment]
Code is always misleading, but it seems that jmxtrans user is created in pre and removed in postrun (around https://github.com/jmxtrans/jmxtrans/blob/master/pom.xml#L1098). And it does not seem that there are any dependencies on the UID. So conditionally creating the user should be fine (RPM is really not my thing, I might be completely wrong ...)

**Comment by hgomez** [comment]
I was looking in original spec file : https://github.com/jmxtrans/jmxtrans/blob/master/rpm/SPECS/jmxtrans.spec :)

**Comment by bijugs** [comment]
Another suggestion is to publish SHA256 checksum for the files so that tools like Chef can perform the verification. [Chef uses SHA256](https://docs.chef.io/resource_remote_file.html#attributes) for checksum verification. Let me know if a new item need to be created.

**Comment by hgomez** [comment]
It will better to 3 create different issues/requests.
Easier to track and fix

**Comment by gehel** [comment]
MD5 and GPG signatures are generated (http://central.maven.org/maven2/org/jmxtrans/jmxtrans/249/). Feel free to send a PR if you want additional signatures ...

**Comment by gehel** [comment]
@hgomez I moved the generation of RPMs to Maven to make it easier to automate the build on travis and to upload everything to Maven central. That might or might not have been a mistake ... but at least RPMs are published with each snapshot now. I have probably broken a few things in the process. All my apologies...

**Comment by hgomez** [comment]
No problem.
Do you want me to check pom vs spec ?

**Comment by gehel** [comment]
I'd be really grateful !

**Comment by hgomez** [comment]
:+1:

**Comment by gehel** [comment]
Closing this as more specific issues have been opened (#280, #281, #282 and #283)
