### ISSUE TITLE
LOG_LEVEL in jmxtrans.sh is broken

### ISSUE THREAD

**Issue by vjanelle** [jmxtrans/jmxtrans#292]
As cited here: https://groups.google.com/forum/#!searchin/jmxtrans/log_level/jmxtrans/NhojsKpu5SU/iW9pX3sRg_EJ

Changing LOG_LEVEL in any of the configuration files does nothing.

**Comment by gehel** [comment]
Yep, logging is a big mess at the moment. It is slowly improving but there is still work to do.

I'm closing this as it is mostly tracked in #215.
