### ISSUE TITLE
Unable to change debug level of the console output

### ISSUE THREAD

**Issue by ayusmand** [jmxtrans/jmxtrans#294]
I am sorry if this is not the right forum to ask these questions.

I have checked out the 249-SNAPSHOT branch and build it locally with my own outputWriters implementations.
I start the jmxtrans from command line using the following:

`<java -Djmxtrans.log.level=10 -jar jmxtrans-249-SNAPSHOT-all.jar -e -f D:\Templates\AyusmanMultiServerConfig1.json -s 5 > D:\JmxTrans\logs\Set6\_Console.log>`

This produces a lot of debug messages in the console:
`<15:04:51.567 [Thread-2] DEBUG c.googlecode.jmxtrans.JmxTransformer - Stopped writer: SimpleCsvWriterForMemory for query: Query [obj=java.lang:type=Memory, resultAlias=null, attr=[HeapMemoryUsage, NonHeapMemoryUsage]]
15:04:51.567 [Thread-2] DEBUG c.googlecode.jmxtrans.JmxTransformer - Stopped writer: SimpleCsvWriter for query: Query [obj=java.lang:type=OperatingSystem, resultAlias=null, attr=[SystemLoadAverage, SystemCpuLoad, ProcessCpuLoad]]
15:04:51.567 [Thread-2] DEBUG c.googlecode.jmxtrans.JmxTransformer - Stopped writer: SimpleCsvWriterForMemory for query: Query [obj=java.lang:type=MemoryPool,name=PS*, resultAlias=, attr=[Name, Usage]]>`

I tried changing the command line java parameter -Djmxtrans.log.level=10 to each of the following
`< -Djmxtrans.log.level=0>`
`< -Djmxtrans.log.level=ERROR >`
`< -Djmxtrans.log.level=1 >`

But the STDOUT log remains at DEBUG level. Is it possible to configure log level in JMXTRANS by commandline parameters?

**Comment by gehel** [comment]
Yes, logging is a mess. #215 is opened to track progress on this front. More specifically, #288 should be merged soon and should fix your specific issue.

I'll close this issue for the moment as it is tracked in #215 and #288.
