### ISSUE TITLE
Writing Kafka Output Writer. 

### ISSUE THREAD

**Issue by utkarshcmu** [jmxtrans/jmxtrans#295]
Feature request : Will be implementing writer to Kafka in JSON/Graphtie text format.

**Comment by gehel** [comment]
Sounds like a good idea. Do you have a pull request ?

**Comment by utkarshcmu** [comment]
I have forked the repository, will be editing and testing in my local repository first. Will submit a pull request soon. :+1:

**Comment by gehel** [comment]
I will be happy to review it !

**Comment by utkarshcmu** [comment]
I am done with my changes in my forked repository. Now, when I am running "mvn clean install", the jar is made. This works perfectly. But when I run "mvn clean install -Prpm" then , build fails with the following error:

[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.2:attached-rpm (attach-rpm) on project jmxtrans: RPM build execution returned: '139' executing '/bin/sh -c cd '/Users/ubhatnagar/jmxtrans/jmxtrans/target/rpm/jmxtrans/SPECS' && 'rpmbuild' '-bb' '--target' 'noarch-apple-mac os x' '--buildroot' '/Users/ubhatnagar/jmxtrans/jmxtrans/target/rpm/jmxtrans/buildroot' '--define' '_topdir /Users/ubhatnagar/jmxtrans/jmxtrans/target/rpm/jmxtrans' 'jmxtrans.spec'' -> [Help 1]

I am trying to build this on my mac. Is there anything I am missing which I need to install except rpm/rpmbuild?

**Comment by gehel** [comment]
I'm not really sure ... Dont you have additional logs ?

There is not much chance that you broke something on the RPM pacakging, so just send the PR and I'll have a look.

**Comment by utkarshcmu** [comment]
Ah..... It was a stupid rpm setup on my machine.... I fixed it.... error doesn't show up anymore. Will be submitting the PR for the KafkaWrite by today. :+1:

**Comment by utkarshcmu** [comment]
We can close this too now. After merging #305
