### ISSUE TITLE
port variable not parsed when using system properties in json file

### ISSUE THREAD

**Issue by yuk1974** [jmxtrans/jmxtrans#298]
Hi,

I have been working with a json file which has a variable configured for the server port number. However it does not get resolved to the actual value I have added to the System using the -Dport=1234 method. When looking at the source code I see that this is indeed not resolved. 

sniplet from the Server.java (com.googlecode.jmxtrans.model)
....
                this.alias = resolveProps(alias);
		this.host = resolveProps(host);
		this.port = port;
		this.username = resolveProps(username);
		this.password = resolveProps(password);
....

I am wondering if this is done with a reason, and if so would like to know the reason. If this is a bug could it please be fixed? I can also contribute the fix myself if preferred.

kind regards and keep up the good work !
Vincent

**Comment by gehel** [comment]
That's definitely a bug. I'd be happy to accept a PR.

I'd like to rewrite part of the configuration parsing to make sure variable substitution is done at load time with a strategy similar to what we have in jmxtrans-embeded : https://github.com/jmxtrans/embedded-jmxtrans/blob/master/src/main/java/org/jmxtrans/embedded/util/json/PlaceholderEnabledJsonNodeFactory.java. If you want to port this approach to jmxtrans, feel free to have a go at it !
