### ISSUE TITLE
cronExpression doesn't work

### ISSUE THREAD

**Issue by Mortinke** [jmxtrans/jmxtrans#309]
I would like define the interval per json configuration file. The cronExpression doesn't work for that.
I defined the following cronExpression "0/10 * * * * *" to start the querys every 10 seconds.

# ConfigFile
 "servers": [
  {
   "username": "controlRole",
   "password": "********",   
   "numQueryThreads": 26,
   "alias": "dev-stage-cassandra1",
   "host": "dev-stage-cassandra1",
   "cronExpression": "0/10 * * * * *",
   "queries": [
........

# LogFile
INFO   | jvm 1    | 2015/06/24 11:35:48 | 11:35:48.627 [ServerScheduler_Worker-1] DEBUG c.googlecode.jmxtrans.jobs.ServerJob - +++++ Started server job: Server [host=dev-stage-cassandra1, port=7199, url=null, cronExpression=0/10 * * * * *, numQueryThreads=26]

**Comment by Dunedan** [comment]
We had a similar issue and noticed that in addition there is a global default setting for ```SECONDS_BETWEEN_RUNS``` which is set to a [default of ```60``` seconds](/jmxtrans/jmxtrans/blob/bded405/jmxtrans/jmxtrans.sh#L48). So maybe you also just need to adjust that as well.

**Comment by gehel** [comment]
Scheduler is far too complex at the moment and needs to be simplified quite a bit. As part of this simplification, I'd like to make sure that it is configureable by server and / or query. That's not going to happen in the short term, but if someone would like to start a PR on this, I'd be happy to provide some help to the best of my ability.

**Comment by gehel** [comment]
I'm trying to get rid of `cronExpression`. Could you try the same with `runPeriodSeconds`? It shoudl work just fine. Closing this at the moment, feel free to re-open if needed.

**Comment by KvMadan** [comment]
> I'm trying to get rid of `cronExpression`. Could you try the same with `runPeriodSeconds`? It shoudl work just fine. Closing this at the moment, feel free to re-open if needed.

It works!
