### ISSUE TITLE
OpenTSDB writer doesn't reconnect after failure...

### ISSUE THREAD

**Issue by mdehus** [jmxtrans/jmxtrans#314]
It seems that the OpenTSDB writer fails to attempt to reconnect after it is disconnected.  I can reliably reproduce this issue by restarting the OpenTSDB daemon.  This is running on a CentOS 6.6 machine. I believe I'm running the latest stable build RPM obtained from maven:  http://central.maven.org/maven2/org/jmxtrans/jmxtrans/250/jmxtrans-250.rpm

The following is the exception message I get in the jmxtrans.log after I restart opentsdb.  These messages never stop coming, and metrics stop populating in opentsdb even after it is brought back online.

IINFO   | jvm 1    | 2015/07/30 22:27:25 | 22:27:25.022 [pool-390-thread-4] ERROR c.g.jmxtrans.jmx.ProcessQueryThread - Error executing query: Query [obj=java.lang:type=OperatingSystem, useObjDomainAsKey:false, resultAlias=sys-flume, attr=[SystemLoadAverage, AvailableProcessors, TotalPhysicalMemorySize, FreePhysicalMemorySize, TotalSwapSpaceSize, FreeSwapSpaceSize, OpenFileDescriptorCount, MaxFileDescriptorCount]]
INFO   | jvm 1    | 2015/07/30 22:27:25 | java.net.SocketException: Broken pipe
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92) ~[na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.net.SocketOutputStream.write(SocketOutputStream.java:115) ~[na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.io.DataOutputStream.writeBytes(DataOutputStream.java:259) ~[na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at com.googlecode.jmxtrans.model.output.OpenTSDBWriter.sendOutput(OpenTSDBWriter.java:121) ~[jmxtrans-250.jar:na]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at com.googlecode.jmxtrans.model.output.OpenTSDBGenericWriter.internalWrite(OpenTSDBGenericWriter.java:282) ~[jmxtrans-250.jar:na]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at com.googlecode.jmxtrans.model.output.BaseOutputWriter.doWrite(BaseOutputWriter.java:151) ~[jmxtrans-250.jar:na]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at com.googlecode.jmxtrans.jmx.JmxQueryProcessor.runOutputWritersForQuery(JmxQueryProcessor.java:75) ~[jmxtrans-250.jar:na]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at com.googlecode.jmxtrans.jmx.JmxQueryProcessor.processQuery(JmxQueryProcessor.java:37) ~[jmxtrans-250.jar:na]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at com.googlecode.jmxtrans.jmx.ProcessQueryThread.run(ProcessQueryThread.java:30) ~[jmxtrans-250.jar:na]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441) [na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_31]
INFO   | jvm 1    | 2015/07/30 22:27:25 |       at java.lang.Thread.run(Thread.java:662) [na:1.6.0_31]

**Comment by gehel** [comment]
Strange ... Quick look at the code indicates that there is an [ugly check](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/OpenTSDBWriter.java#L110) of the validity of the socket. Internet broken at home and fairly busy these days, but I'll try to have a look this weekend.

**Comment by gehel** [comment]
I just released [version 251](https://repo1.maven.org/maven2/org/jmxtrans/jmxtrans/251/). Fairly sure it does not fix your problem, but just to be sure, could you have a try at it ?

**Comment by mdehus** [comment]
That took care of it and solved the problem.  Thank you very much for the quick turn around!
