### ISSUE TITLE
2 level filtering

### ISSUE THREAD

**Issue by prabcs** [jmxtrans/jmxtrans#317]
Hello Folks,

I'm using jmxtrans with Ganglia. I want to use obj as:-

 "obj": "kafka.cluster:type=Partition,name=UnderReplicated,topic=*,partition=*"

This will allow me to publish UnderReplicated partitions for all the partitions for all the topics

How can this be made possible in the json that jmxtrans reads ?

Thanks,
prabcs

**Comment by gehel** [comment]
The [Google groups](https://groups.google.com/forum/#!forum/jmxtrans) is probably a better place for this kind of question. That being said:

You should be able to use something similar to:

    "obj": "kafka.cluster:type=Partition,name=UnderReplicated,*"

I'm not completely sure I understand your issue. What is not working?

**Comment by prabcs** [comment]
For Kafka, some MBeans are not available in the first level e.g.:-

I've created some topics in kafka cluster:-
kafka.cluster:type=Partition,name=UnderReplicated,topic=topic1,partition=0
kafka.cluster:type=Partition,name=UnderReplicated,topic=topic1,partition=1
kafka.cluster:type=Partition,name=UnderReplicated,topic=topic1,partition=2
kafka.cluster:type=Partition,name=UnderReplicated,topic=topic1,partition=3

kafka.cluster:type=Partition,name=UnderReplicated,topic=topic2,partition=0
kafka.cluster:type=Partition,name=UnderReplicated,topic=topic2,partition=1
kafka.cluster:type=Partition,name=UnderReplicated,topic=topic2,partition=2
kafka.cluster:type=Partition,name=UnderReplicated,topic=topic2,partition=3

So, in this case, I would like to give a regex at the topic level:-

kafka.cluster:type=Partition,name=UnderReplicated,topic=*

because the topics are dynamically going to increase, hence the MBeans for the topics are also going to increase with time. Also, the number of partitions can keep on varying with time.
Because of that, I want to use a regex with JMX, to filter first the topic and then the partitions
I want to report per partition of every topic in ganglia


Does that explain ?

**Comment by gehel** [comment]
If I understand correctly, you would like Jmxtrans to aggregate data from each partition for a given topic? Is that correct? Jmxtrans does not support this kind of scenario. It can only directly publish data from a JMX bean to a backend, with no transformation. What you can do is use wildcards to publish all metrics and use your backend to do aggregation. I'm not familiar with Ganglia, but I'm sure that it can do some sort of aggregation.

**Comment by prabcs** [comment]
Yes. Correct. Ganglia can do the aggregation. Please have a look at this image and tell me the corresponding json for reporting partition level stats:-

<img width="1277" alt="screen shot 2015-08-11 at 4 46 54 pm" src="https://cloud.githubusercontent.com/assets/4270624/9196396/ae0e6bd6-4048-11e5-9d51-f9248e0e9684.png">


As you can see in the image, I have 2 topics: 'fromIndiaWithLove' and 'hehe'

If I would like to fetch the attributes for all partitions of the topic: 'hehe', this is the regex I would be using:-

"obj" : "kafka.cluster:type=Partition,name=UnderReplicated,topic=hehe,partition=*"
Right now, when I use a single '*', I can use typeNames to put "partition" as in:-
"typeNames": ["partition"]
This helps me report per partition stats for the topic 'hehe'

But, if I want to report all the topics and all the partitions, I cant do this:-

"obj" : "kafka.cluster:type=Partition,name=UnderReplicated,topic=*,partition=*"

When I use the above obj, I want to report to ganglia as the topic name and partition name
I cant have 2 typenames: one for the topic and the other for the partition.

Can this be done via jmxtrans ?

**Comment by gehel** [comment]
I did not actually check the answer below, but I think that the following should do what you want:

    "obj": "kafka.cluster:type=Partition,name=UnderReplicated,*"
    "typeNames" : ["topic", "partition"]

**Comment by prabcs** [comment]
Great. Thanks for your help.
It Works !
Appreciate your time on this.
