### ISSUE TITLE
Add a license to the repo

### ISSUE THREAD

**Issue by mbrukman** [jmxtrans/jmxtrans#330]
Could you please add an explicit LICENSE file to the root of the repo so that it's clear under what terms you're providing it, and under what license you expect the contributions to be? Thanks!

**Comment by gehel** [comment]
That sounds like a very reasonable request! License is MIT as indicated in the [pom.xml](https://github.com/jmxtrans/jmxtrans/blob/master/pom.xml#L22). If you have time to send a PR, I'll accept it right away ... Else I'll try to find some time to do it ...

**Comment by mbrukman** [comment]
Sure, happy to do so! Just let me know what the year and copyright owner should be, since the MIT license requires these two items.

**Comment by gehel** [comment]
I'm not really sure what year should be in a license. The first commit on the project seems to be from [2010](https://github.com/jmxtrans/jmxtrans/commits/master?page=24).

**Comment by lookfirst** [comment]
The current year.

**Comment by gehel** [comment]
If we want to make license explicit, we should probably use [license-maven-plugin](http://code.mycila.com/license-maven-plugin/) and make sure we have a license header is each file.
