### ISSUE TITLE
error using cloudwatch output writer

### ISSUE THREAD

**Issue by nelg** [jmxtrans/jmxtrans#334]
Hi,

I'm keen to use jmxtrans to output metrics to cloud watch.   Trying the example here: 
https://github.com/jmxtrans/jmxtrans/wiki/CloudWatchWriter

On Centos7, with RPM: http://central.maven.org/maven2/org/jmxtrans/jmxtrans/251/jmxtrans-251.rpm

with only changes to the host, alias and port, I get a stack trace in the logs.  In short, is says:

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "region": com.amazonaws.AmazonWebServiceClient#setRegion(1 params) vs com.amazonaws.AmazonWebServiceClient#setRegion(1 params) (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.ArrayList[0]->
java.util.ArrayList[0]->java.util.ArrayList[0])

Short version here: http://pastebin.com/Apk6ZSWs

I can provide a full trace if needed.

The config file I have tried is just a simple test:
```json
{
   "servers":[
      {
         "alias":"testhost",
         "host":"localhost",
         "port":"1105",
         "queries":[
            {
               "obj":"java.lang:type=OperatingSystem",
               "attr":[
                  "SystemLoadAverage"
               ],
               "resultAlias":"jvm.cpu",
               "outputWriters":[
                  {
                     "@class":"com.googlecode.jmxtrans.model.output.CloudWatchWriter",
                     "settings":{
                        "namespace":"jmx"
                     }
                  }
               ]
            }
         ]
      }
   ]
}
```

**Comment by gehel** [comment]
Strange ... The [unit tests for CloudWatchWriter](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-cloudwatch/src/test/java/com/googlecode/jmxtrans/model/output/CloudWatchWriterTests.java) are very minimal. This seems like something we should be able to validate as a unit test... so we should have one. I'm absolutely unable to have a look before at least a week (sorry). Any chance you could write a unit test to reproduce the issue ?

Thanks for the report anyway !
