### ISSUE TITLE
New query option: useAllTypeNames

### ISSUE THREAD

**Issue by bm371613** [jmxtrans/jmxtrans#336]
I would like to add a new option to `Query`, `useAllTypeNames`. It would make it possible to define a simple `*:*` query and still have keys like `kafka.server.BrokerTopicMetrics.BytesInPerSec.topic_name.Count`.

Would you merge that feature? Do you have any thoughts to share?

**Comment by gehel** [comment]
This sounds like a reasonable option. Let's see how the implementation looks like. If you have some code, show it and we'll start the discussion... As this feature is core to JmxTrans, I will insist on a good unit test coverage, but outside from that, it sounds like a good idea.
