### ISSUE TITLE
is it possible to run jmxtrans with multiple json files?

### ISSUE THREAD

**Issue by fudy** [jmxtrans/jmxtrans#341]
I have many json configure files. I want to run jmxtrans with more than one json files, like this:
./jmxtrans.sh start 1.json 2.json
but I find jmxtrans only load 1.json
then I start it with 2.json by the following command
./jmxtrans start 2.json
I get the following errors:
jmxtrans appears to already be running @ pid: 27489

**Comment by gehel** [comment]
By default, jmxtrans will load all files in /var/lib/jmxtrans. You can modify this directory by setting the `JSON_DIR` variable in `/etc/sysconfig/jmxtrans`. Alternatively, you can run the JmxTrans jar file directly, and give it the path to a single configuration file with the `-f` option (have a look at [CliArgumentParser](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-core/src/main/java/com/googlecode/jmxtrans/cli/CliArgumentParser.java) for all CLI options).

The `jmxtrans appears to already be running` error that you are seeing is fairly straight forward ... You are trying to start JmxTrans twice, you did not shutdown the first instance.

**Comment by fudy** [comment]
thanks, I wil try to edit JSON_DIR

**Comment by gehel** [comment]
Closing this as it seems resolved. Feel free to re open or contact the google group : groups.google.com/forum/#!forum/jmxtrans
