### ISSUE TITLE
How to share writer between multiple queries?

### ISSUE THREAD

**Issue by dadmin-admin** [jmxtrans/jmxtrans#351]
Hello. I wanna get information from multiple jxm objects and use same writer (`KeyOutWriter`). How can I do it?

**Comment by gehel** [comment]
Short answer: you can't.

Long answer, you can generate the configuration from template to reduce duplication. There is a python script bundled with JMXTrans : https://github.com/jmxtrans/jmxtrans/wiki/YAMLConfig
