### ISSUE TITLE
Use TcpOutputWriter for Sensu and OpenTSDB

### ISSUE THREAD

**Issue by gehel** [jmxtrans/jmxtrans#354]
Both Sensu and OpenTSDB use a TCP based protocol. We should reuse the same implementation os the new Graphite2 OutputWriter.

**Comment by gehel** [comment]
Sensu already done.

**Comment by AlbanSeurat** [comment]
New pull request https://github.com/jmxtrans/jmxtrans/pull/413

**Comment by gehel** [comment]
fixed by #413
