### ISSUE TITLE
rpm failed to install on CentOS 7

### ISSUE THREAD

**Issue by depend** [jmxtrans/jmxtrans#365]
```shell
rpm -i jmxtrans-252.rpm
```
```shell
error: Failed dependencies:
        /usr/bin/lsb_release is needed by jmxtrans-252-1.noarch
```

I am able to install using yum:
```shell
yum --nogpgcheck localinstall jmxtrans-252.rpm
```

**Comment by gehel** [comment]
There is an install time dependency on `lsb_release`, which should be provided by the `redhat-lsb` package. Yum will resolve this dependency, which is exactly what you should do. If you want to do the installation directly with `rpm` it is your job to manually install dependencies...

I'll close this as "work as designed". Feel free to re-open if you disagree.

**Comment by kevinconaway** [comment]
@gehel I'd like to reopen this if you don't mind continuing the discussion.  I ran in to the same issue as @depend.

Is the `lsb_release` dependency even necessary?

I'm looking at how its used in the pom:
https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans/pom.xml#L336

`lsb_release` is used to get the distro name / version and the `useradd` command is based on that data.  However, the command is nearly the same except that the arguments to useradd are in a different order and split over multiple lines.  

Can we just use the same command?  If so, that would eliminate this dependency.

**Comment by gehel** [comment]
@kevinconaway yes, we could re-open this. I'd actually prefer to open a new issue as the current RPM works, it's just sub-optimal. Feel free to send a PR !

Side note: I'd really like to have better testing of the RPM (and DEB). We should add a build step that install the packages on various distro, using docker (or a similar techno) and validates that JmxTrans starts correctly after installation.

As always, I sadly do not have enough time on my hands to implement all the things I'd like. I need your help!
