### ISSUE TITLE
can't locate config file on CentOS 7

### ISSUE THREAD

**Issue by depend** [jmxtrans/jmxtrans#366]
Everything runs fine but I can't find the config file.
```shell
ls /etc/sysconfig/jmxtrans
ls: cannot access /etc/sysconfig/jmxtrans: No such file or directory
```

**Comment by gehel** [comment]
RPM have been modified to use Tanukisoft wrapper. Configuration can be found in /etc/jmxtrans. Documentation should be updated (my bad...).
