### ISSUE TITLE
Best practice to work with jmx authentication

### ISSUE THREAD

**Issue by depend** [jmxtrans/jmxtrans#372]
What's the best practice to work with jmx authentication? I would like to check in my json query file to source control but don't want to include jmx username/password. Is there a way to refer to environment variables in the json file?

**Comment by gehel** [comment]
That's probably a discussion for the [Google group](https://groups.google.com/forum/#!forum/jmxtrans). That being said:

* use a configuration management tool (Puppet / Chef / whatever) and use the templating and credential management facilities of those tools
* yes, you can use environment variables anywhere in the json config. As always, documentation is lacking, but have a look in the sources for the details. Your entry poitn should be https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/PropertyResolver.java

I'm closing this issue for now, feel free to reopen or send the conversation to the Google group.

**Comment by depend** [comment]
Thank you for pointing me to the wring direction.
