### ISSUE TITLE
Small intervals cause lost metrics

### ISSUE THREAD

**Issue by luxifr** [jmxtrans/jmxtrans#375]
Hi,

I'm trying to run jmxtrans for collecting metrics in a 10 second interval and sending it to a graphite instance.

cron expression is: "0/10 * * * * * *" and I'm querying ~80 values from 13 objects, some from fields, some from function return values

I have already tried assigning more query threads than I have values to query and that still doesn't help.

Am I doing something wrong or is jmxtrans just not suited for collecting that amount of data in such short intervals?

**Comment by gehel** [comment]
I could have a look at our numbers to make sure, but we did collect a lot more than that with a single jmxtrans instance at some point (probably around 10K metrics / seconds). 80 values every 10 seconds is really very low.

Could you take a few thread dumps and attach then to this issue so that I can have a look?

Thanks!

**Comment by luxifr** [comment]
Wow, what a quick response!

There you go :-)
[jmxtrans.tdumps.zip](https://github.com/jmxtrans/jmxtrans/files/63812/jmxtrans.tdumps.zip)

**Comment by gehel** [comment]
Which version of jmxtrans are you using? Looking at the thread dumps, it seems to be a fairly old version. If that's the case, could you upgrade to the latest version?

**Comment by gehel** [comment]
A few remarks:

* the version of jmxtrans you are using tries to do a read on the network to validate the connections to the graphite server. This is a very much not scalable way of validating connection: as soon as your graphite server slows even just a little bit (or your network), jmxtrans will crawl to a halt. This seems to be the case here.
* thread dumps show that most of your threads are doing nothing. You can definitely reduce the number of threads quite a lot
* you have a lot of threads, but only a few connections to the graphite server, so in fact, all thread are just waiting for the connection to become available (no, this is not configureable at the moment).

**Comment by luxifr** [comment]
Yeah, I've been using that for a while now - I'll try the latest version. The latest version will not be affected as much by the latency to the graphite server? Can I increase the connections to the graphite server jmxtrans will try to use?

**Comment by luxifr** [comment]
Okay, the current version seems to perform better... however I found why I had used that other one until now :-) It was a fork, actually, that added support for jmx operations, which I need unfortunately. I see if I can find the fork and if it kept up with you otherwise... If not: could you add this support into your project?

**Comment by gehel** [comment]
I'm closing this for now as it seems to be resolved in recent jmxtrans versions. Adding support for operations is tracked at #376.
