### ISSUE TITLE
Could not get the attribute of string 

### ISSUE THREAD

**Issue by tangsz123** [jmxtrans/jmxtrans#398]
When I use jmxtrans get weblogic Mbean attributes,  only get number-type attribute, could not get the attribute of string。

**Comment by tangsz123** [comment]
"obj" : "com.bea:Name=myserver,Type=ServerRuntime",
"resultAlias": "",
"attr" : [ "Name","State","ListenPort","ActivationTime" ]

When I run jmxtrans, I can get to the value of ListenPort and ActivationTime, but could not get the value of  Name and State

**Comment by gehel** [comment]
What OutputWriter are you using? Could you post the full configuration?

**Comment by tangsz123** [comment]
{
  "servers" : [ {
    "port" : "20001",
    "host" : "127.0.0.1",
    "queries" : [ {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.StackdriverWriter",
        "settings" : {
            "url":"http://127.0.0.1:5000/receive?type=WebLogicState&localhost=127.0.0.1:70001&param={\"dataType\":\"serverInfo\",\"server\":\"myserver\",\"ListenPort\":7001}",
            "token":"123456"
        }
      } ],
      "obj" : "com.bea:Name=myserver,Type=ServerRuntime",
      "resultAlias": "",
      "attr" : [ "Name","SSLListenPort","AdminServer","State","ListenAddress","ListenPort","ActivationTime" ]
    },
    {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.StackdriverWriter",
        "settings" : {
            "url":"http://127.0.0.1:5000/receive?type=WebLogicState&localhost=127.0.0.1:70001&param={\"dataType\":\"serverMemory\",\"server\":\"myserver\"}",
            "token":"123456"
        }
      } ],
      "obj" : "com.bea:ServerRuntime=myserver,Name=myserver,Type=JVMRuntime",
      "attr" : [ "HeapFreeCurrent", "HeapSizeCurrent","HeapSizeMax","HeapFreePercent"],
      "resultAlias": ""
    },
    {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.StackdriverWriter",
        "settings" : {
            "url":"http://127.0.0.1:5000/receive?type=WebLogicState&localhost=127.0.0.1:70001&param={\"dataType\":\"serverThread\",\"server\":\"myserver\"}",
            "token":"123456"
        }
      } ],
      "obj" : "com.bea:ServerRuntime=myserver,Name=ThreadPoolRuntime,Type=ThreadPoolRuntime",
      "attr" : [ "ExecuteThreadIdleCount", "ExecuteThreadTotalCount","CompletedRequestCount","PendingUserRequestCount","QueueLength","Suspended"],
      "resultAlias": ""
    },
    {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.StackdriverWriter",
        "settings" : {
            "url":"http://127.0.0.1:5000/receive?type=WebLogicState&localhost=127.0.0.1:70001&param={\"dataType\":\"serverConnectionPool\",\"server\":\"myserver\",\"dataSource\":\"mysql-dataSource\"}",
            "token":"123456"
        }
      } ],
      "obj" : "com.bea:ServerRuntime=myserver,Name=mysql-dataSource,Type=JDBCConnectionPoolRuntime",
      "attr" : [ "WaitingForConnectionHighCount", "JDBCConnectionPoolRuntimeMBean","WaitingForConnectionCurrentCount","MaxCapacity","WaitSecondsHighCount","ActiveConnectionsCurrentCount","ActiveConnectionsHighCount","LeakedConnectionCount"],
      "resultAlias": ""
    },
    {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.StackdriverWriter",
        "settings" : {
            "url":"http://127.0.0.1:5000/receive?type=WebLogicState&localhost=127.0.0.1:70001&param={\"dataType\":\"serverConnectionPool\",\"server\":\"myserver\",\"dataSource\":\"testSource\"}",
            "token":"123456"
        }
      } ],
      "obj" : "com.bea:ServerRuntime=myserver,Name=testSource,Type=JDBCConnectionPoolRuntime",
      "attr" : [ "WaitingForConnectionHighCount", "JDBCConnectionPoolRuntimeMBean","WaitingForConnectionCurrentCount","MaxCapacity","WaitSecondsHighCount","ActiveConnectionsCurrentCount","ActiveConnectionsHighCount","LeakedConnectionCount"],
      "resultAlias": ""
    },
    {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.StackdriverWriter",
        "settings" : {
            "url":"http://127.0.0.1:5000/receive?type=WebLogicState&localhost=127.0.0.1:70001&param={\"dataType\":\"webapp\",\"ContextRoot\":\"emc\",\"server\":\"myserver\"}",
            "token":"123456"
        }
      } ],
     "obj" : "com.bea:ServerRuntime=myserver,Name=myserver_/emc,ApplicationRuntime=WebRoot,Type=WebAppComponentRuntime",
     "attr" : [ "ContextRoot", "ApplicationIdentifier","Name","Status","OpenSessionsCurrentCount","OpenSessionsHighCount","SessionsOpenedTotalCount"],
         
      "resultAlias": ""
    }

    ],
    "numQueryThreads" :10
  } ]
}


      } ],

**Comment by tangsz123** [comment]
when I use "com.googlecode.jmxtrans.model.output.KeyOutWriter", I  still cant not get the value of Name and State 。Here are the configuration：
                     {
  "servers" : [ {
    "port" : "20001",
    "host" : "127.0.0.1",
    "queries" : [ {
         "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.KeyOutWriter",
        "outputFile" : "out2.txt",
        "maxLogFileSize" : "10MB",
        "maxLogBackupFiles" : 200,
        "delimiter" : "\t",
        "debug" : true,
        "typeNames" : ["name"]
      } ],
      
     "obj" : "com.bea:Name=myserver,Type=ServerRuntime",
      "resultAlias": "",
      "attr" : [ "Name","SSLListenPort","AdminServer","State","ListenAddress","ListenPort","ActivationTime" ]
    }

    ],
    "numQueryThreads" :2
  } ]
}

Here are the results：

         localhost:jmxtrans tangsz$ cat out2.txt 
                   127_0_0_1_20001..SSLListenPort	7002	1452566171693
                   127_0_0_1_20001..ListenPort	7001	1452566171693
                   127_0_0_1_20001..ActivationTime	1452566086437	1452566171693
