### ISSUE TITLE
jmxtrans fails to reconnect if a JVM got restarted

### ISSUE THREAD

**Issue by somechris** [jmxtrans/jmxtrans#399]
Assume jmxtrans is configured to pick up metris from some JVM-foo.

Starting JVM-foo.
Then starting jmxtrans.
Everything is fine. jmxtrans picks up the metrics.

After some time JVM-foo has issues and needs to be restarted.
While JVM-foo is down, jmxtrans complains that it can no longer connect to JVM-foo, which is expected.
But after JVM-foo came back up, jmxtrans is still complaining that JVM-foo is unconnectable.

jmxtrans is stuck on the old failed connections, and does not try to reconnect.

**Comment by gehel** [comment]
Which version of JMXTrans are you using?

**Comment by somechris** [comment]
master. (18f32f3aebfb29b77655c372ebee248bd9fb04c1)
