### ISSUE TITLE
Question about KeyOutWriter

### ISSUE THREAD

**Issue by Wildpipe** [jmxtrans/jmxtrans#408]
Hi,

I am using jmxtrans to collect information about Queues and other things from Jboss A-MQ. I am currently using the KeyOutWriter to write information gathered to a csv file on disk. It is working great except for not being able to query the A-MQ application about the name of a Queue. I can query the application about almost anything as long as the answer to a query is not a string.

Now I am no expert in Java but I think I might have spotted why this is and am wondering if you could help me figure out a solution to this. In the file KeyOutWriter.java on line 139 to 143 I found the following code:

if (NumberUtils.isNumeric(values.getValue())) {

logger.info(KeyUtils.getKeyString(server, query, result, values, typeNames, null) + delimiter
+ values.getValue().toString() + delimiter + result.getEpoch());
}

To my understanding this code will make sure that the value I recieve is a numeric and not a string. Would removing this numeric check break anything in the keyoutwriter? Please correct me if I am wrong about this theory.

What I want to achieve is to use the keyoutwriter and query my application for the name of a specific queue and write it to a file.

**Comment by gehel** [comment]
Your assumption is pretty good. JmxTrans is meant to collect metrics, and most metrics backend are expecting values to be time series (so numeric data). In the case of the KeyOutWriter, it might make sense to support non numeric values as well. This seems to me to be kind of a edge case that I'm not completely sure that JmxTrans should support (not completely convinced either way at the moment, try to convince me ...).

Note that KeyOutWriter will probably dispear at some point to be replaced by [Slf4JOutputWriter](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/Slf4JOutputWriter.java). Slf4JOutputWriter is sadly not yet documented enough, but in short, it will send everything to the Slf4J logger and let you configure any output that you want by modifying the backing logger configuration.

**Comment by Wildpipe** [comment]
I have a few hundred queues in A-MQ and query the application with these attributes:

"obj" : "org.apache.activemq:type=Broker,brokerName=*,*",
"attr" : [ "ProducerCount", "ConsumerCount", "QueueSize", "DequeueCount", "EnqueueCount", "Name" ]

This data is not very useful if I am not able to retrieve the name to which the metric belong. I will just end up with a file containing thousands of useless datapoints. 

I have tried to solve this by trying different writers and using the stdoutwriter I am able to use the exact same query and recieve the name of the queue. I also tried the jmxtrans-agent which gave me the possiblity of using resultAlias and rewrite the result based on object names:

resultAlias="activemq.%brokerName%.queue.%destinationName%.QueueSize"

But the jmxtrans-agent will only connect to local pids which is deal-breaker for me.

A possible solution could be to make use of resultAlias but I couldn't find any documentation that jmxtrans supports the use of variables like the jmxtrans-agent. 

I'll take a look at the Sif4JoutPutWriter, thanks.

**Comment by gehel** [comment]
What you probably want in your case is to use

    "obj" : "org.apache.activemq:type=Broker,*",
    "typeNames" : [ "brokerName" ],
    "attr" : ...

This should capture the `brokerName` and add it to the metric name.

And yes, the templating of metric names in jmxtrans-agent is nice! We should port that to jmxtrans!

**Comment by Wildpipe** [comment]
Oh, that's awesome! Thank you so so much. 
I totally did not get the purpouse of the typeNames setting. 

I agree with porting the templating of metric names for sure!

**Comment by gehel** [comment]
Closing this as your issue seems to be resolved. Feel free to reopen if needed.
