### ISSUE TITLE
Remove `lsb_release` dependency from RPM

### ISSUE THREAD

**Issue by kevinconaway** [jmxtrans/jmxtrans#417]
@gehel per my comment on #365, I don't see why the dependency for `lsb_release` is needed in the RPM:

> I'm looking at how its used in the pom:
> https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans/pom.xml#L336
>
>lsb_release is used to get the distro name / version and the useradd command is based on that data. >However, the command is nearly the same except that the arguments to useradd are in a different order >and split over multiple lines.

I'm happy to submit a PR on this but I wanted to have an extra set (or more) of eyes on that code to see if I'm missing something.

It looks like @magullo submitted the original fix, maybe he has some insight.

**Comment by gehel** [comment]
Just send the pull request, so we can have the discussion around the code. I'll make sure to review it. If you can go the extra mile (or extra 100 miles) and add integration tests for the packaging, we can be sure that it works! (But yes, I understand that integration tests on the packaging is a big task).

**Comment by kevinconaway** [comment]
Do you have a list of platforms that should be tested?

**Comment by gehel** [comment]
Ideally, the main distro: RHEL, Centos, Fedora, Debian, Ubuntu, ... Realistically, the one you have time...

**Comment by kevinconaway** [comment]
Well if we went the Docker approach it _should_ be relatively easy to re-use the same test harness on different docker images so thats why I was curious about the different releases / versions

It looked like there were specific issues with RHEL5 and Suse (per https://github.com/jmxtrans/jmxtrans/pull/328)

**Comment by gehel** [comment]
You would make me so happy if you added integration tests for packages! Beer on me if you come to Switzerland!

**Comment by kevinconaway** [comment]
This should be doable in a week or three

**Comment by magullo** [comment]
The fix was made for EAP5, I know would be better to remove dependency for lsb_release, but could not find a workaround.
I'm not very much involved in Docker, so I cannot help here.

**Comment by kevinconaway** [comment]
For jboss? Do you remember the context of the changes?

**Comment by kevinconaway** [comment]
@gehel do you have any thoughts on how these tests should run?  Should they be run manually?  As part of every travis build?  A special travis build plan? 

How are the rpm/debs generated now?

**Comment by gehel** [comment]
@kevinconaway ideally, they should run on travis. Last time I checked, it was not possible to do nested docker on travis, so that might not be an option.

Manual run would already be great.

I'd love to have those tests piloted by maven (activated by a specific profile), but a shell script outside of maven control is fine too.

In the end, having tests is in any case better than not having them, we can always improve on how to run them ...

**Comment by kevinconaway** [comment]
@gehel I'm looking at the https://github.com/jmxtrans/jmxtrans/blob/master/travis-script.sh, is there a reason why the `rpm` and `deb` profiles are not activated for pull requests?  I would think we would want to build the packages and test them for all PRs, right?

**Comment by gehel** [comment]
If we actually have tests, yes, it might make sense. But gpg keys will not be available, so we need to disable signing the packages.

**Comment by magullo** [comment]
Sorry for the slow answer.
RH5 and rpmbuild do not provide macro for getting OS_RELEASE and REDHAT_RELEASE, so I had to find a way to retrieve them. lsb_release was the quinck answer.
As far as things go, we could consider removing RH5 support.

**Comment by kevinconaway** [comment]
Thanks @magullo.  I added a test for centos 5.11, do you think that should cover it?

@gehel thanks for your patience and support on this one.  Let me know if there are any further issues with the build, I'm going to push forward with improving the docker plugin so that it doesn't fail when the containers can't be stopped.

**Comment by gehel** [comment]
There are lots of issues with everything :-)

One thing that would be great would be to fix the publication of the maven site. Some work was started on #299 but never merged. I rewrote some of it and merged it, but there are still issues. And we could improve it quite a bit (aggregated reports is one thing that comes to mind).

**Comment by magullo** [comment]
@kevinconaway no problem, did you push to your repo? As I said, I think RHEL5 support could be removed. At least I'll keep a local branch only for my (few) machines.

**Comment by kevinconaway** [comment]
Sorry I'm not following what you mean.  The docker tests are all in master now and the lsb_release dependency is gone.

@gehel I think we can close this, right?

**Comment by gehel** [comment]
Yes, looks like we can close it... Thanks!
