### ISSUE TITLE
Get OpenSource licenses for JmxTrans contributors

### ISSUE THREAD

**Issue by gehel** [jmxtrans/jmxtrans#442]
As suggested by @cyrille-leclerc I'm contacting JetBrains to renew our IntelliJ license (JetBrains is kind enough to offer free licenses for OpenSource projects). Those licenses are now nominative, so let me know if you want one. The current team is:

* @lookfirst 
* @hgomez 
* @cyrille-leclerc 
* @bijugs 
* @kerlandsson 
* @zonArt

**Comment by gehel** [comment]
I will probably get back to JetBrains by tomorrow, so let me know quickly if possible. In any case, we can request license again at a later time if needed.

**Comment by cyrille-leclerc** [comment]
Thanks @gehel !

**Comment by gehel** [comment]
I just requested 5 licenses. We should be able to upgrade to more if we need at some point. I'll transfer the licenses as soon as I get them.

**Comment by gehel** [comment]
Just got the licenses from JetBrains (communicated to the team via private channel).

JetBrains asks (very nicely, this is not a condition to get the licences or to renew them) if we would like to add a JetBrains logo to our project page to show their support (that phrasing seems backward, late here and my English is not what it should be).

Exactly:
> If you feel that IntelliJ IDEA has helped you a great deal, we'd be grateful if you could mention JetBrains' support for your project by placing an IntelliJ IDEA logo at the project's website. Please, follow the link if you wish to choose the logo: http://www.jetbrains.com/company/press/materials.html

I am already privately recommending IntelliJ to anyone I know, I'm not sure how I feel about putting a commercial company logo on the project page. Your call (all of you).

**Comment by utkarshcmu** [comment]
Why not Apache?

**Comment by gehel** [comment]
@utkarshcmu not sure I understand what you mean...

**Comment by utkarshcmu** [comment]
@gehel Oops, I misunderstood this thread/issue. Please ignore my question. :(

**Comment by bijugs** [comment]
Since IntelliJ is helping the project by providing the license +1 to have their company logo as ``Thank You``.

**Comment by gehel** [comment]
My issue is that we could end up with a lot of logos. SonarSource, CloudBees, Nespresso (to some extent), ... for providing resources both in people and in infrastructure. At the same time, JetBrains are the only one who asked (to my knowledge).

**Comment by cyrille-leclerc** [comment]
I +1 a "thank you" page listing all the companies who help the project giving free access to their paying products / services and for the companies who give engineering time.

**Comment by gehel** [comment]
Ok, [thank you page](https://github.com/jmxtrans/jmxtrans/wiki/Thanks) created. Feel free to add other "thank you" for other companies...

Closing this issue as resolved...
