### ISSUE TITLE
same error as #443

### ISSUE THREAD

**Issue by vfork001** [jmxtrans/jmxtrans#445]
same error, issue #443 
[11 Apr 2016 09:02:07] [jmxtrans-result-5] 72612  WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=AvailableProcessors, className=com.
.
.
.

**Comment by vfork001** [comment]
{
  "servers" : [ {
    "port" : "8999",
    "host" : "hostxxxx",
    "username" : "jmxMonitor",
    "password" : "passwordXXX",
    "queries" : [ {
     	"outputWriters" : [ {
            "@class" : "com.googlecode.jmxtrans.model.output.OpenTSDBWriter", 
	    "port" : 4242, 
	    "host" : "localhost", 
	    "tags" : { "POD": "Pod1_dc2", "host": "pd1phx-aaa-01", "type" : "aaaserver" }
      	} ],
   	"obj" : "java.lang:type=OperatingSystem",
	"resultAlias": "os",
	"attr" : [ 
		"AvailableProcessors", 
		"SystemLoadAverage", 
		"ProcessCpuTime", 
		"OpenFileDescriptorCount", 
		"MaxFileDescriptorCount" ]

	},{
[deleted...]
 } ],
 "numQueryThreads" : 2
 } ]
}

**Comment by gehel** [comment]
Closing this and re-opening #443
