### ISSUE TITLE
java >= 1.7 is needed by jmxtrans-254-1.noarch？

### ISSUE THREAD

**Issue by zywei** [jmxtrans/jmxtrans#446]
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

what's wrong?

**Comment by gehel** [comment]
It all depends on how you installed Java. The check will be done by the package manager, checking that there is a package providing java >= 1.7. If you installed java by hand, the check will fail. You can always ignore the failed dependency and force the install...

**Comment by zywei** [comment]
yes, then i installed java by rpm,i worked.
