### ISSUE TITLE
statsd underflow

### ISSUE THREAD

**Issue by filippog** [jmxtrans/jmxtrans#448]
hi,
sort of related to underflow reported in #272, I've experienced the same problem when sending to C-based statsd daemons (https://github.com/armon/statsite in this case) where it'd fail to `strtod` the input.  Is limiting to C's MIN_DOUBLE for statsd metrics something you'd consider as well? thanks!

**Comment by gehel** [comment]
Sure, that sounds like a good idea. Maybe add a flag to enable it. But I think the loss of precision is negligible (or at least, I don't see a use case where that kind of precision would be required).

**Comment by filippog** [comment]
:+1: thanks @gehel for the quick fix!

**Comment by gehel** [comment]
@filippog don't thank me too much... latest release has a few more time consuming problems to fix. This was an easy one. But I'm not ready to push a new release...
