### ISSUE TITLE
JMXTrans Creating Duplicate OutputWriters

### ISSUE THREAD

**Issue by kevinconaway** [jmxtrans/jmxtrans#453]
As of 254, JMXTrans is creating duplicate outputwriters during initialization, only one of which is used.  This leads to unnecessary resource consumption.   #441 has more details

**Comment by kevinconaway** [comment]
@gehel thinking about this a bit.  One of the issues here is that the OutputWriters are instantiated via the JSON deserialization process so there isn't a great way to reuse the objects.

For some old style Writers (like GraphiteWriter, StatsDWriter etc) the connections to the underlying systems are made in the constructor itself which further complicates things.

I see that most of these old style Writers have deprecation warnings.  Is there a reason we're keeping the code around?  Would it make sense just to have the class inherit from (or use) the corresponding v2 OutputWriterFactory instead?

That should maintain backwards compatibility while allowing the outputwriters to be reused.

**Comment by gehel** [comment]
We have made the same conclusions. The current way of having the configuration model very close to the runtime model is limiting. The introduction of OutputWriterFactories was a first step in decoupling those a bit more. At some point we will probably need to increase this decoupling even more.

At some point yes, we should completely remove the "old" output writers, in favor of the new factory based output writers. I'm not yet ready to do this removal as the new output writers have not yet been battle tested. This specific issue (#453) show that the new output writers are completely broken at the moment. So keeping both until we are confident that the new ones are perfectly working seems like a reasonable thing to do, even if it has a non trivial cost.

**Comment by gehel** [comment]
@kevinconaway I'd really appreciate if you could have a look at #456 before I merge it. I did so many things wrong around this issue that a second look could help (or if anyone wants to comment on my ugly code, please do!).

**Comment by kevinconaway** [comment]
Will review, thanks
