### ISSUE TITLE
how to distinguish metric value is GAUGE or COUNTER

### ISSUE THREAD

**Issue by modeyang** [jmxtrans/jmxtrans#465]
in jmxtrans， has any example or codes performs like that? thanks.

**Comment by gehel** [comment]
I'm not exactly sure what you are looking for. You might want to have a look at the [StatsDWriter](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/StatsDWriter2.java). There is no computation a such, the `bucketType` is a configuration parameter, which is then used in sending metrics to StatsD.

If you give more context on what you are looking for, we might be able to help you better...

**Comment by modeyang** [comment]
thanks @gehel ,  metric type in open falcon is the same meaning with `bucketType` in **StatsDWriter**.

**Comment by gehel** [comment]
Closing this as it seems OP has the answer requested.
