### ISSUE TITLE
jmxtrans fails starting on centos 7

### ISSUE THREAD

**Issue by KlavsKlavsen** [jmxtrans/jmxtrans#485]
After building rpm from and installing it - it can't start. it fails with this in systemd logs:
```
Aug 24 13:36:20 myhostname.example.org systemd[1]: Starting JMX Transformer - more than meets the eye...
Aug 24 13:36:20 myhostname.example.org jmxtrans[26076]: Starting jmxtrans: [  OK  ]
Aug 24 13:36:20 myhostname.example.org systemd[1]: Failed to read PID from file /var/run/jmxtrans.pid: Invalid argument
Aug 24 13:36:20 myhostname.example.org systemd[1]: jmxtrans.service never wrote its PID file. Failing.
Aug 24 13:36:20 myhostname.example.org systemd[1]: Failed to start JMX Transformer - more than meets the eye.
Aug 24 13:36:20 myhostname.example.org systemd[1]: Unit jmxtrans.service entered failed state.
Aug 24 13:36:20 myhostname.example.org systemd[1]: jmxtrans.service failed.

```
/var/run is there (ofcourse :)

**Comment by gehel** [comment]
It seems there is an inconsistency in the JSW configuration. Startup script expect PID file in /var/run/jmxtrans/jmxtrans.pid, but JSW configuration expects it in /var/run/jmxtrans.pid. The probable fix lies in [jmxtrans/pom.xml:L267](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans/pom.xml#L267), but I just don't have time to check at the moment.

**Comment by KlavsKlavsen** [comment]
I tried latest snapshot v260 - but that does not generate a systemd file as part of the rpm package ?

**Comment by gehel** [comment]
Nope, the .deb and .rpm packages have not yet migrated to systemd (definitely something we should do).

**Comment by KlavsKlavsen** [comment]
after learning a bit more of systemd - I ended up with this systemdfile - which actually works :)

and which means you  no longer depend on the init.d script at all.

# Systemd unit file for jmxtrans
#
[Unit]
Description=JMX Transformer - more than meets the eye
After=syslog.target network.target

[Service]
Type=forking
PIDFile=/run/jmxtrans/jmxtrans.pid
EnvironmentFile=/etc/sysconfig/jmxtrans
User=jmxtrans
ExecStart=/usr/share/jmxtrans/bin/jmxtrans start

[Install]
WantedBy=multi-user.target

**Comment by KlavsKlavsen** [comment]
you seem to no longer have systemd file in the code repo ? otherwise I'd gladly make a PR.. but I don't know where to put it.

**Comment by gehel** [comment]
It is very unclear where to put a systemd unit at the moment. Probably somewhere in the jmxtrans/jmxtrans module. I need to do some refactoring on the packaging and provide systemd packaging. I'll add the systemd unit as well.

**Comment by petems** [comment]
@KlavsKlavsen I've found that this works better

```
[Unit]
Description=JMX Transformer - more than meets the eye
After=syslog.target network.target

[Service]
Type=forking
User=jmxtrans
Group=jmxtrans
# Run ExecStartPre with root-permissions
PermissionsStartOnly=true
ExecStartPre=-/usr/bin/mkdir /run/jmxtrans/
ExecStartPre=/usr/bin/chown -R jmxtrans:jmxtrans /run/jmxtrans/
PIDFile=/var/run/jmxtrans/jmxtrans.pid
ExecStart=/usr/share/jmxtrans/bin/jmxtrans start

[Install]
WantedBy=multi-user.target
```

As the file from the package is lost on reboot, this will make sure that the folder exists with the right permissions 👍

**Comment by petems** [comment]
Ok, even better, more recent versions of systemd have a `RuntimeDirectory` parameter, this seems more suited than creating the directory automatically:

```
RuntimeDirectory=, RuntimeDirectoryMode=

Takes a list of directory names. If set, one or more directories by the specified names will be created below /run (for system services) or below $XDG_RUNTIME_DIR (for user services) when the unit is started, and removed when the unit is stopped. The directories will have the access mode specified in RuntimeDirectoryMode=, and will be owned by the user and group specified in User= and Group=. Use this to manage one or more runtime directories of the unit and bind their lifetime to the daemon runtime.
```
