### ISSUE TITLE
Images missing from wiki pages

### ISSUE THREAD

**Issue by dwo** [jmxtrans/jmxtrans#488]
Some wiki pages, such as [Queries](https://github.com/jmxtrans/jmxtrans/wiki/Queries) contain images that are no longer available through googlecode.com eg: http://jmxtrans.googlecode.com/svn/wiki/ehcache-example.png

I'd be happy to correct these, as the images are recoverable from the googlecode SVN archive -- just not sure if they've already been copied somewhere else that I should correct the URLs to? If they haven't been copied over already, is there someplace that would be good to put them now?

**Comment by gehel** [comment]
Thanks for taking the time to report this! Documentation, as always is lagging behind...

I'm not sure if those images are recoverable. I think google code still offer a way to download repos, so we might dig in there. But honestly, that particular image is just an example of the kind of graphs you can get out of jmxtrans + graphite. It might be easier to upload a new one. And the example can be with ehcache or with something else.

If you want to upload a new one, please go ahead!

**Comment by dwo** [comment]
Hey @gehel, I actually downloaded the archive from Google Code and found the images: I'm just not sure where I should upload them to, or where I should put them in a PR to jmxtrans so that they're embeddable in the wiki. Any guidance?

**Comment by gehel** [comment]
@dwo Thanks! We should probably follow the maven site structure and put those images in <repo>/src/site/images.

**Comment by dwo** [comment]
OK, I've corrected the wiki, so closing this.
