### ISSUE TITLE
How to scale out JMXTrans?

### ISSUE THREAD

**Issue by Colstuwjx** [jmxtrans/jmxtrans#490]
As I seen the doc said that JMXTrans support millions of node,  but how to scale out JMXTrans itself?
I could not find any doc about this, wishes  your reply.

Many thanks!

**Comment by gehel** [comment]
I depends a lot on your use case (as always). But if you outgrow what jmxtrans can handle on a single server, just split the load on multiple servers. Or a fairly usual strategy is to have a jmxtrans instance on each of the monitored server, that way jmxtrans scales with the systems under monitoring.

**Comment by Colstuwjx** [comment]
OK, It really makes things simple and easy!
