### ISSUE TITLE
How to connect JMXServiceURL in jmxtranss

### ISSUE THREAD

**Issue by murugurams** [jmxtrans/jmxtrans#497]
Hi,

I'm new to jmxtrans.Recently started using this agent.

I have a requirement to monitor jmx counters which is exposed through jmxservice url .i.e service:jmx:rmi://[host[:port]][urlPath] 

in configuration i couldn't find any url option. 
Please guide me if there is an option for that.

Thanks in Advance
Ram

**Comment by gehel** [comment]
In most cases, just setting host and port in the jmxtrans configuration file should work (see https://github.com/jmxtrans/jmxtrans/wiki/Queries for examples). You can set the full URL instead if needed / wanted. I don't think this is well documented, but you can have a look at the [Server class](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/Server.java#L167). JMX is an old and crappy protocol, welcome to our mess!

**Comment by murugurams** [comment]
Thanks a lot for your quick response.. 

It is working fine..
Regards
Ram
