### ISSUE TITLE
Telegraf Writer

### ISSUE THREAD

**Issue by codecounselor** [jmxtrans/jmxtrans#499]
It would be great to have a writer for Telegraf that supports an alias much like the InfluxDB writer does.  I don't see that anyone is working on this.  I'd be happy to make an attempt at writing one. 

Unless I'm missing an existing way to send InfluxDB Line Protocol metrics to Telegraf? 
Example `user.logins,service=payroll,region=us-west:1|c`
Taken from: https://www.influxdata.com/getting-started-with-sending-statsd-metrics-to-telegraf-influxdb/ 

This is working great in the StatsD java client, and I'd like to do the same with jmxtrans.  It should just be some minor tweaks to extend the StatsDWriter.

**Comment by codecounselor** [comment]
I started working on this.  Need to spend some more time with it and add some tests but I've accomplished most of my goal for my own use case.

https://github.com/jmxtrans/jmxtrans/compare/master...codecounselor:master

**Comment by gehel** [comment]
This looks good! A few more unit tests and we should be ready to merge...

Thanks!

**Comment by willmpls** [comment]
I had the same need and actually wrote something similar over the last two days.  I based my work heavily on the TCollector writer, so it uses a generic message formatter, allows jexl expressions to build the metric names, includes writers for both UDP and TCP, and has an option to write all keys as tags since they're sometimes not known ahead of time in wildcard situations.  

Here's what I have so far:

https://github.com/jmxtrans/jmxtrans/compare/master...willmpls:influxdb_lineproto

Just wanted to throw this out there so I don't end up with a custom fork with slightly different InfluxDB line protocol support!

**Comment by codecounselor** [comment]
Thanks for sharing, I just took a quick look and will explore it in more detail this weekend.  It seems that you're still targeting InfluxDB though right?  I noticed that Telegraf does not support the sending of epoch (unless I did something wrong)

Maybe it would make more sense to include my changes inside of the Influx module so we can share any duplicate logic?  

I was trying to keep the Telegraf writer as simple as possible, and wasn't thinking beyond StatsD support with the addition of tags.

**Comment by willmpls** [comment]
I'm outputting in InfluxDB line protocol which is supported by By both InfluxDB directly and by Telegraf via it's udp_listener and tcp_listener input types:

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/udp_listener
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tcp_listener

So, using these outputs JMXTrans can write via udp or tcp to Telegraf, and Telegraf can in turn send output to one or more output plugins.

The Telegraf inputs support epoch as it's used in the InfluxDB line protocols.  Is that the epoch you were thinking of?

**Comment by willmpls** [comment]
For reference, here is output generated for some common mbeans, followed by the configuration used:

Output:

```
$ ./udp_server.py
starting up on localhost port 5101

waiting to receive message
received 416 bytes from ('127.0.0.1', 64268)
jvm.Memory.HeapMemoryUsage,testTag2=myvalue2,attr=init,type=Memory value=268435456 1477061132727000000
jvm.Memory.HeapMemoryUsage,testTag2=myvalue2,attr=committed,type=Memory value=257425408 1477061132727000000
jvm.Memory.HeapMemoryUsage,testTag2=myvalue2,attr=max,type=Memory value=3817865216 1477061132727000000
jvm.Memory.HeapMemoryUsage,testTag2=myvalue2,attr=used,type=Memory value=41037840 1477061132727000000


waiting to receive message
received 480 bytes from ('127.0.0.1', 61708)
jvm.GarbageCollector.CollectionCount,testTag=myvalue,name=PS_MarkSweep,type=GarbageCollector value=0 1477061132727000000
jvm.GarbageCollector.CollectionTime,testTag=myvalue,name=PS_MarkSweep,type=GarbageCollector value=0 1477061132727000000
jvm.GarbageCollector.CollectionCount,testTag=myvalue,name=PS_Scavenge,type=GarbageCollector value=1 1477061132731000000
jvm.GarbageCollector.CollectionTime,testTag=myvalue,name=PS_Scavenge,type=GarbageCollector value=9 1477061132731000000
```

Config:

```
{
  "servers": [
    {
      "alias": "macbook",
      "host": "127.0.0.1",
      "port": "9100",
      "username": "jmx",
      "password": "jmx",
      "queries": [
        {
          "attr": [
            "CollectionCount",
            "CollectionTime"
          ],
          "obj": "java.lang:type=GarbageCollector,name=*",
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.InfluxDBUDPWriterFactory",
              "host": "localhost",
              "port": 5101,
              "typeNames": [],
              "metricNamingExpression": "alias + '.' + typename['type'] + '.' + attribute",
              "mergeTypeNamesTags": false,
              "tags": { "testTag": "myvalue" },
              "addHostnameTag": false,
              "allKeysAsTags": true,
              "tagName": "",
              "flushStrategy": "always",
              "flushDelayInSeconds": 1
            }
          ],
          "resultAlias": "jvm"
        },
        {
          "attr": [
            "HeapMemoryUsage"
          ],
          "obj": "java.lang:type=Memory",
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.InfluxDBUDPWriterFactory",
              "host": "localhost",
              "port": 5101,
              "typeNames": [],
              "metricNamingExpression": "alias + '.' + typename['type'] + '.' + attribute",
              "mergeTypeNamesTags": false,
              "tags": { "testTag2": "myvalue2" },
              "addHostnameTag": false,
              "allKeysAsTags": true,
              "tagName": "attr",
              "flushStrategy": "always",
              "flushDelayInSeconds": 1
            }
          ],
          "resultAlias": "jvm"
        }
      ]
    }
  ]
}
```

**Comment by codecounselor** [comment]
That is helpful, you just made me realize that I'm not using Telegrafs UDP plugin, I'm actually sending it to the Telegraf StatsD plugin which supports tags.  So I didn't quite frame my problem correctly, I will go about renaming my OutputWriter to something like `StatsDTelegrafWriter`.  

I will also consider using your solution directly, but I think I might still get some benefit out of StatsD.

**Comment by willmpls** [comment]
Makes sense.  I'll open up a separate PR for the Influx line protocol tcp/udp output writers once I kick the tires a bit more.  If you have any feedback as far as those go let me know!

**Comment by gehel** [comment]
Closing this as #501 is merged.
