### ISSUE TITLE
change jmxtrans job interval

### ISSUE THREAD

**Issue by david-chnisc** [jmxtrans/jmxtrans#514]
It's a really a great tool on jmx management, I'm trying to use jmxtrans to monitor Tomcat through some attributes of MBean. But I think jmxtrans default job shcedule interval is a little long, is there any methods to change the interval? Through the configuration of /etc/jmxtrans/wrapper.conf or any other methods?

**Comment by gehel** [comment]
In your configuration files, the `server` object can take a `runPeriodSeconds` attribute, which is probably what you want. You can also modify the wrapper.conf to pass the `-s` or `--run-period-in-seconds` parameter to jxmtrans. We should have a global configuration file for jmxtrans, but we don't (yet). A global config file would make configuration a bit easier than passing arguments around through all the different startup mechanism.

And no, this isn't documented... it should be!

**Comment by david-chnisc** [comment]
@gehel Great thanks to you, I'll try the methods above, then listing the result.

**Comment by david-chnisc** [comment]
I can easily achieve my goal via pass `runPeriodSeconds` attribute to server object in my JSON configuration file, and it well worked. Thank you @gehel
