### ISSUE TITLE
File not found - lib/jmxtrans-all.jar

### ISSUE THREAD

**Issue by veerareddyganta** [jmxtrans/jmxtrans#517]
I performed the following steps mentioned in the wiki (https://github.com/jmxtrans/jmxtrans/wiki/Installation) to install jmxtrans and got "File not found - lib/jmxtrans-all.jar" error when the command - "./jmxtrans.sh start" was run from ~/jmxtrans-260/bin folder.

1. Downloaded jmxtrans-260.rpm
2. Installed using the command - rpm -i jmxtrans-260.rpm
3. Downloaded distribution - jmxtrans-260-dist.tar.gz
4. gunzip jmxtrans-260-dist.tar.gz
5. tar -xvf jmxtrans-260-dist.tar
6. cd ~/jmxtrans-260/bin
7. ./jmxtrans.sh start

It is giving "File not found - lib/jmxtrans-all.jar".  I can see jmxtrans-all.jar inside jmxtrans-260/lib folder though.

**Comment by gehel** [comment]
Packaging is crap. I'm trying to find some time to clean this up... 

In the meantime, you can set the [`$JAR_FILE` environment variable](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans/jmxtrans.sh#L45) (either directly in your shell, or via `/etc/sysconfig/jmxtrans`) to the absolute path to the jmxtrans-all.jar file.

**Comment by veerareddyganta** [comment]
Thank you for quick reply.
