### ISSUE TITLE
Jmxtrans spooling results?

### ISSUE THREAD

**Issue by ceeeekay** [jmxtrans/jmxtrans#523]
I've got a basic query set up, so far checking one stat on one server every 5 seconds, and using the Graphite writer.

Everything is mostly fine and I can see the results in Graphite, however there's a huge delay going on (up to 10 mins) before the results appear in Graphite. This is not so fine as I'm trying to build a real-time dash.

Restarting jmxtrans causes the backlog to show up immediately.

Is there a setting for this, or something I can poke?

Thanks!

**Comment by gehel** [comment]
Sorry for the delay... Yes, there is a solution: configure a more aggressive `flushStrategy`. For example add `flushStrategy: always` to the outputwriter configuration. Documentation is behind (feel free to update it), but you can have a look at the code of [GraphiteWriterFactory](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/GraphiteWriterFactory.java#L72-L73) and [FlushStrategyUtils](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/pool/FlushStrategyUtils.java#L37-L47).

**Comment by ceeeekay** [comment]
Nice - `flushStrategy: always` has solved it for me.

Thanks!

**Comment by gehel** [comment]
Feel free to update the docs as a thanks you :)
