### ISSUE TITLE
Filter out Non-Number Numbers

### ISSUE THREAD

**Issue by kevinconaway** [jmxtrans/jmxtrans#539]
There are some JMX metrics that will return numbers like `Double.NaN`, `Double.POSITIVE_INFINITY` or `Double.NEGATIVE_INFINITY`.  These metrics will pass the `NumberUtils.isNumeric` check because it simply does an `instanceof Number` check.  However these values can't really be processed by Graphite (or perhaps any other down stream system, but I can't speak for those) so I think they should be filtered out.

@gehel thoughts here?  Happy to submit a PR if needed

**Comment by gehel** [comment]
@kevinconaway: yes, a PR would be great! I don't know if we currently have any backend that would support those "almost number" values, but it seems likely that some backend out there does support them (even if jmxtrans does not have integration with them yet). So fixing this in the GraphiteWriter seems to make sense. Extracting a utility method that could be reused in other writers would be great!

**Comment by kevinconaway** [comment]
Thanks for merging this so quickly.  It would be good if a release could be made with these changes when you have time.

Thanks!

**Comment by gehel** [comment]
Release in progress: https://travis-ci.org/jmxtrans/jmxtrans/builds/186118029

**Comment by itzg** [comment]
FWIW, this is similar to the issue I faced+fixed with the statsd writer https://github.com/jmxtrans/jmxtrans/pull/535 , but in that case their protocol had a way to convey a "non number".

**Comment by tanuj83** [comment]
do we have solution for Kafka as well ?  #751
