### ISSUE TITLE
jmxtrans-263.rpm doesn't detect java properly.

### ISSUE THREAD

**Issue by raju-divakaran** [jmxtrans/jmxtrans#549]
Hello,

I am trying to install jmxtrans-263.rpm on CentOS 7.3. 

I am having java installed and version 1.8.

But when I try to install jmxtrans-263.rpm, it throws below error

`error: Failed dependencies:
	java >= 1.7 is needed by jmxtrans-263-1.noarch
`
Anyone facing the same ? 

Thanks,

~Raju.

**Comment by gehel** [comment]
Did you install java via RPM or manually? If RPM does not know about it, it will not find the dependency...

**Comment by raju-divakaran** [comment]
Java isn't installed via rpm. I overcome it by issuing nodeps while installing the rpm of jmxtrans

**Comment by gehel** [comment]
I'm closing this, RPM is not expected to know about packages not managed by RPM...
