### ISSUE TITLE
Support of Jolokia as input

### ISSUE THREAD

**Issue by vromero** [jmxtrans/jmxtrans#550]
[Jolokia](https://jolokia.org/) is an HTTP/JSON interface for JMX. It only uses one port (that is predefined) and it has 1-1 mappings to JMX calls.

Given how difficult it is to configure JMX in the container world because of the random RMI nature of JMS plus the need of knowing the external ip for the rmi server in the service itself. It would be valuable to support jolokia as an input.

**Comment by gehel** [comment]
Jmxtrans does have the infrastructure in place to support multiple outputs, it does not have anything similar for inputs. The current goal of jmxtrans is to simplify working with JMX. So is the goal of Jolokia (which is btw a great project). There are multiple solutions to easily bridge Jolokia with a number of backends. [Diamond](https://github.com/python-diamond/Diamond) comes to mind.

Sorry, but there isn't much chance to integrate Jolokia as input in the foreseeable future.
