### ISSUE TITLE
How to run this code for "monoiter" hadoop job performance?

### ISSUE THREAD

**Issue by rahulmistry9** [jmxtrans/jmxtrans#554]
please show the steps to run this code.

**Comment by gehel** [comment]
You probably want to have a look at [our wiki](https://github.com/jmxtrans/jmxtrans/wiki). Documentation is not as good as it should and not always up to date, but it is a good starting point (feel free to improve our documentation as you go through it).

I'm closing this issue for the moment, feel free to create another one if you have more specific questions.
