### ISSUE TITLE
KeyOutWriter ignores maxLogBackupFiles in settings map.

### ISSUE THREAD

**Issue by raymond-wells** [jmxtrans/jmxtrans#559]
**How to reproduce**

Configure a `KeyOutWriter` with a `maxLogFileSize` and `maxLogBackupFiles` in the `settings` block.

```json
{
  "servers": [
    {
      "host": "localhost",
      "port": 5000,
      "queries": [
        {
          "obj": "java.lang:type=Threading",
          "attr": [
            "ThreadCount"
          ],
          "resultAlias": "threading",
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.KeyOutWriter",
              "settings": {
                "outputFile": "metrics.log",
                "maxLogFileSize": "100MB",
                "maxLogBackupFiles": 7
              }
            }
          ]
        }
      ]
    }
  ]
}
```

** Expected behavior **

JMXTrans should rotate older metrics logs out to numbered log files when `metrics.log` reaches `100MB`.

** Actual behavior **

JMXTrans truncates `metrics.log` when it reaches `100MB`.

If you move `maxLogBackupFiles` out of `settings`, `KeyOutWriter` will rotate logs normally.

**Comment by gehel** [comment]
The fix you have looks good, I'm pulling it... Thanks!

Side note: we should get rid of this settings map and just use attributes on the OutputWriter themselves.
