### ISSUE TITLE
"runPeriodSeconds" in "servers" does not work

### ISSUE THREAD

**Issue by JaapD** [jmxtrans/jmxtrans#560]
In the configurationfile I used "cronExpression" but got a message that "cronExpression" is deprecated. I replaced it by "runPeriodSeconds". The deprecated message did not show up again, but jmx trans runs every minute, regardless of the value I enter.

**Comment by gehel** [comment]
Looks like a stupid bug... Fix coming up...

**Comment by JaapD** [comment]
Thanks! Any idea when this will be included in a new release?

**Comment by gehel** [comment]
I can do a release this morning...

**Comment by gehel** [comment]
New release should be available on maven central...

**Comment by JaapD** [comment]
I just tested it and it works. Thanks!

**Comment by gehel** [comment]
Good! Let us know if there is anything else not working :)
