### ISSUE TITLE
InfluxDbWriterFactory ignores tagNames

### ISSUE THREAD

**Issue by fksimon** [jmxtrans/jmxtrans#567]
The InfluxDbWriterFactory.java take sin the typeNames property but it is never used.   So when doing wild card queries like Name=* the field names overlap each other.

Example

{
  "outputWriters": [{
    "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
    "url" : "http://influxdb:8086/",
      "typeNames": ["scope","name"]
  }],
    "obj": "org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Latency",
    "resultAlias": "clientRequest",
    "attr": [
      "Count"
    ]
},
{
  "outputWriters": [{
    "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
    "url" : "http://influxdb:8086/",
      "typeNames": ["scope","name"]
  }],
    "obj": "org.apache.cassandra.metrics:type=ClientRequest,scope=Read,name=Timeouts",
    "resultAlias": "clientRequest",
    "attr": [
      "Count"
    ]
},

The above should write out as
Measurement clientRequest
Attributes:
Read.Latency.Count
Read.Timeouts.Count

However currently it writes out as 
Measurement clientRequest
Attributes:
Count
Count

Other than making a unique measurement for each there is no work around.

**Comment by fksimon** [comment]
PR created to fix https://github.com/jmxtrans/jmxtrans/pull/568

**Comment by fksimon** [comment]
Change merged

**Comment by gehel** [comment]
@fksimon let me know if you need a new release...

**Comment by fksimon** [comment]
I built it local and just deployed in my own container.   No rush.  Thanks for approving though

Thanks
Fran
