### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [jmxtrans/jmxtrans#595]
Based on https://github.com/jmxtrans/jmxtrans/releases/latest it's not clear to me whether 246 or 266 is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by gehel** [comment]
I completely forgot about Github releases! Latest releases are always pushed to Maven Central. So 266 is the current latest. Releases are reputed stable unless proven otherwise. Intermediate development is published as [snapshots](https://oss.sonatype.org/content/repositories/snapshots/org/jmxtrans/jmxtrans/) following the usual Maven practices.

Not sure what to do about the Github releases. Should we keep them as archived? The main [jmxtrans README](https://github.com/jmxtrans/jmxtrans) does document where releases are, but that might not be enough. Feel free to submit a PR to that README file to clarify...

**Comment by ilovezfs** [comment]
You just need to delete the explicit releases on GitHub, which should not disrupt the tags themselves.

https://github.com/jmxtrans/jmxtrans/releases/tag/v246
https://github.com/jmxtrans/jmxtrans/releases/tag/v245
https://github.com/jmxtrans/jmxtrans/releases/tag/v244
https://github.com/jmxtrans/jmxtrans/releases/tag/v243

**Comment by gehel** [comment]
Ok, releases are deleted on Github. This should be enough to cose this issue, feel free to reopen if needed.

**Comment by ilovezfs** [comment]
@gehel yup, looks good! https://github.com/jmxtrans/jmxtrans/releases/latest now resolves to https://github.com/jmxtrans/jmxtrans/releases as expected. Thanks!

**Comment by gehel** [comment]
Note that I'm entirely unsure how MacOS support is... I don't own a Mac myself. If you find anything that would make sense to be corrected, please send a PR!

**Comment by ilovezfs** [comment]
@gehel the analytics are
```
Josephs-MacBook-Pro:Formula joe$ brew formula-analytics --days-ago=100 jmxtrans
install events in the last 100 days for jmxtrans
=====================================================================================================
1 | jmxtrans                                                                           | 85 | 100.00%
=====================================================================================================
Total                                                                                  | 85 |    100%
=====================================================================================================
Josephs-MacBook-Pro:Formula joe$ brew formula-analytics --days-ago=100 --install-on-request jmxtrans
install_on_request events in the last 100 days for jmxtrans
=====================================================================================================
1 | jmxtrans                                                                           | 43 | 100.00%
=====================================================================================================
Total                                                                                  | 43 |    100%
=====================================================================================================
```
and, no complaints, so I think it's fine :)
