### ISSUE TITLE
Collecting metrics stops when at least one node is down

### ISSUE THREAD

**Issue by kipwoker** [jmxtrans/jmxtrans#626]
My collegue wrote (https://gitter.im/jmxtrans/jmxtrans?at=58e4fdaaad849bcf425405a5)

> Hi! I’m observing a strange side effect when using jmxtrans (build 260) to collect metrics from Cassandra nodes. When at least one node is down, I observe incorrect or missing datapoints on all other metrics coming from the same instance of jmxtrans.
What am I doing wrong?

We've tried to fix this. But I have no idea what's wrong.
There are my investigation results. May be it helps to get answer.

First of all we've covered by logs next methods

- Server.execute
- JmxUtils.processServer

After that we're replayed this scenario at production. One cassandra node was closed by firewall to test instance of jmxtrans.

What actually happened.

Logs from JmxUtils.processServer when we closed node by firewall and our thread pool limit set to 10:
1. ThreadPool ActiveCount=10 | QueueSize=10. All items in queue for node which is down.
2. After one minute we have no metrics from another nodes.
3. After three minutes ThreadPool has stats ActiveCount=10 | QueueSize=2530 and no errors at log.
4. Rollback firewall block.
5. After few seconds app wrote to log some errors about connection timeout. Like this:
```
[01 Dec 2017 14:16:14] [jmxtrans-query-0] 379842 ERROR (com.googlecode.jmxtrans.jmx.ProcessQueryThread:57) - Error executing query Query(objectName=org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=MemtableSwitchCount, keys=[], attr=[Value], typeNames=[], resultAlias=ColumnFamily, useObjDomainAsKey=false, allowDottedKeys=true, useAllTypeNames=false, outputWriterInstances=[GraphiteWriter(pool=org.apache.commons.pool.impl.GenericKeyedObjectPool@29f9efa0, rootPrefix=DevOpsTest.Cassandra.WebCluster, address=graphite-relay/7.7.7.7:2003, onlyOnceLogger=com.googlecode.jmxtrans.util.OnlyOnceLogger@457b9597)]) on server Server(pid=null, host=cassandra-134, port=8899, url=service:jmx:rmi:///jndi/rmi://cassandra-134:8899/jmxrmi, cronExpression=null, numQueryThreads=20)
java.rmi.ConnectException: Connection refused to host: 192.168.191.2; nested exception is: 
	java.net.ConnectException: Connection timed out (Connection timed out)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130)
	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.queryNames(Unknown Source)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.queryNames(RMIConnector.java:847)
	at com.googlecode.jmxtrans.model.Query.queryNames(Query.java:208)
	at com.googlecode.jmxtrans.model.Server.execute(Server.java:288)
	at com.googlecode.jmxtrans.jmx.ProcessQueryThread.run(ProcessQueryThread.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 14 more
```
6. After few seconds app collects metrics again. Thread pool queue decreased.

So @gehel was right

> that's where we should have a circuit breaker... You probably have threads just waiting for the dead server to respond and eating up the threadpool

And we've decided to dump threads through jstack.

First interesting thing: a lot of heartbeat threads slept:
```
Threads count: 194
 - java.lang.Thread.sleep(long) @bci=0 (Compiled frame; information may be imprecise)
 - com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker.run() @bci=35, line=175 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)

Threads count: 150
 - java.lang.Thread.sleep(long) @bci=0 (Compiled frame; information may be imprecise)
 - com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker.run() @bci=35, line=175 (Compiled frame)
 - java.lang.Thread.run() @bci=11, line=745 (Compiled frame)

Threads count: 52
 - java.lang.Thread.sleep(long) @bci=0 (Compiled frame; information may be imprecise)
 - com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker.run() @bci=35, line=175 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Compiled frame)
```
I don't think it's okay but it's not source of our topic problem.

So let's have a look for next 10 threads:
```
Threads count: 10
 - java.net.PlainSocketImpl.socketConnect(java.net.InetAddress, int, int) @bci=0 (Compiled frame; information may be imprecise)
 - java.net.AbstractPlainSocketImpl.doConnect(java.net.InetAddress, int, int) @bci=64, line=350 (Compiled frame)
 - java.net.AbstractPlainSocketImpl.connectToAddress(java.net.InetAddress, int, int) @bci=23, line=206 (Compiled frame)
 - java.net.AbstractPlainSocketImpl.connect(java.net.SocketAddress, int) @bci=78, line=188 (Compiled frame)
 - java.net.SocksSocketImpl.connect(java.net.SocketAddress, int) @bci=381, line=392 (Compiled frame)
 - java.net.Socket.connect(java.net.SocketAddress, int) @bci=179, line=589 (Compiled frame)
 - java.net.Socket.connect(java.net.SocketAddress) @bci=3, line=538 (Compiled frame)
 - java.net.Socket.<init>(java.net.SocketAddress, java.net.SocketAddress, boolean) @bci=82, line=434 (Compiled frame)
 - java.net.Socket.<init>(java.lang.String, int) @bci=34, line=211 (Compiled frame)
 - sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(java.lang.String, int) @bci=6, line=40 (Compiled frame)
 - sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(java.lang.String, int) @bci=65, line=148 (Compiled frame)
 - sun.rmi.transport.tcp.TCPEndpoint.newSocket() @bci=62, line=613 (Compiled frame)
 - sun.rmi.transport.tcp.TCPChannel.createConnection() @bci=22, line=216 (Compiled frame)
 - sun.rmi.transport.tcp.TCPChannel.newConnection() @bci=101, line=202 (Compiled frame)
 - sun.rmi.server.UnicastRef.invoke(java.rmi.Remote, java.lang.reflect.Method, java.lang.Object[], long) @bci=65, line=130 (Compiled frame)
 - com.sun.jmx.remote.internal.PRef.invoke(java.rmi.Remote, java.lang.reflect.Method, java.lang.Object[], long) @bci=9 (Compiled frame)
 - javax.management.remote.rmi.RMIConnectionImpl_Stub.queryNames(javax.management.ObjectName, java.rmi.MarshalledObject, javax.security.auth.Subject) @bci=27 (Compiled frame)
 - javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.queryNames(javax.management.ObjectName, javax.management.QueryExp) @bci=76, line=847 (Compiled frame)
 - com.googlecode.jmxtrans.model.Query.queryNames(javax.management.MBeanServerConnection) @bci=6, line=208 (Compiled frame)
 - com.googlecode.jmxtrans.model.Server.execute(com.googlecode.jmxtrans.model.Query) @bci=79, line=288 (Compiled frame)
 - com.googlecode.jmxtrans.jmx.ProcessQueryThread.run() @bci=8, line=54 (Compiled frame)
 - java.util.concurrent.Executors$RunnableAdapter.call() @bci=4, line=511 (Compiled frame)
 - java.util.concurrent.FutureTask.run() @bci=42, line=266 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1142 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=617 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)
```

Problem localized at Server.execute when it tries to call `query.queryNames(connection)`
```
for (ObjectName queryName : query.queryNames(connection)) {
    results.addAll(query.fetchResults(connection, queryName));
}
```

It corresponds to our logs. We've got waiting after borrow connection from mbeanPool.

According to [sun.rmi Properties documentation](https://docs.oracle.com/javase/7/docs/technotes/guides/rmi/sunrmiproperties.html) we can tune timeouts. So we did it.
We set:
sun.rmi.transport.connectionTimeout=5000
sun.rmi.transport.proxy.connectTimeout=5000
sun.rmi.transport.tcp.handshakeTimeout=5000
sun.rmi.transport.tcp.responseTimeout=5000

Nothing helps.
May be we lose something?

I understand that we can write circuit breaker like tracking health of replica or somthing like that. But first of all we should learn how to cancel dead connections, right?

**Comment by kipwoker** [comment]
Try to resolve at branch https://github.com/kipwoker/jmxtrans/tree/socket_timeout_fix

**Comment by gehel** [comment]
You might want to have a look at #566 which brings a full circuit breaker implementation for output writers. The same implementation could be used for servers as well. Using the same circuit breaker will likely help consistency and thus make code easier to understand.

That being said, the idea in the socket_timeout_fix branch look like exactly the right thing to do!

**Comment by kipwoker** [comment]
@gehel you did great job.
We can forget about my branch. But I want to make some improvement in your branch.
May you grant me access to your branch?
I think this commits may be useful:
https://github.com/jmxtrans/jmxtrans/commit/56bb2efd4ef4a2e0b4a6ad2b962039ece757fe01
https://github.com/jmxtrans/jmxtrans/commit/5a7b26fedb7b85faab62e2c870410e8dad6dc257
https://github.com/jmxtrans/jmxtrans/commit/eab65aaf72a108e7c9af23ab838edd693f96d579

**Comment by gehel** [comment]
Those 3 commits look like they are not directly related to my PR, we could merge them on their own. So feel free to open specific PR for them. That would allow to move forward a bit faster, I'm fairly busy at the moment and don't know when I'll have time to finish work on #566.

**Comment by kipwoker** [comment]
@gehel 
I've made some tests with my implementation of circuit breaker.
My commits with socket timeout tuning not helps so much as I expected.

Previously metrics collecting stopped when at least one node is down. But now it stops for 5-7 minutes. Because thread pool fills up during all threads at dead node waiting for socket timeout.

I see here two solutions:
1. Thread pool can be more smart. For example, if 2/3 of pool filled by one node then rest 1/3 part can't be used by this node. It's some kind of throttling solution.
2. Change logic and use separate thread pool for each node.

First solution can be more complexive. But may be it provide more performance.

Second solution is more easier in implementation. I see it like new parameter in yaml/json config. For each node user can define thread pool size and queue capacity. If settings weren't defined use default settings. For backward compatibility it can be implemented as another strategy which can be swtiched by config file or cli params.
It also can be good solution because of metrics collectiong evenly for each node. So there are no overhead.

What do you think about it?

**Comment by gehel** [comment]
I'm not sure what circuit breaker implementation you are talking about. The commits I have seen are more about failing early on bad JMX connections than about an actual circuit breaker. I think we should put a circuit breaker on `Server.execute()`, which would prevent any work to go on a server that has problems. I think that should be the first step.

Having a processing scheme that is both robust and fair is a hard problem :)

Other things we _should_ / _could_ do:

* increase the default size of the `queryProcessorExecutor` pool (not really a solution, but might help)
* have a thread pool per server (better isolation, but worse in term of resource utilization, probably worth it)
* ...

Thanks for digging into this!

**Comment by kipwoker** [comment]
I'm talking about circuit breaker that i've made some days ago. It's just for experiment: https://github.com/kipwoker/jmxtrans/commit/081853cbee5a2df188f2c9e88bbe737a8526b5bc

>I think we should put a circuit breaker on Server.execute(), which would prevent any work to go on a server that has problems.

Anyway you need to wait timeout.
For example you have timeout = 20 seconds and three nodes (one of them dead). During 20 seconds all threads in pool will be acquired by dead node. Any alive node will be unavailable. Yes, you can tune your thread pool settings but it's very float value. You need to understand how it works inside to tune it.
I've tried to increase size of pool but it's just a temporary solution.

> better isolation, but worse in term of resource utilization, probably worth it

That's why I want to implement thread pool per server like another strategy of app behaviour. I think user should have a choice.
Also I expect as user that my metrics collecting seperately depending on server. So according to this seems logic to rework architecture to separate way.

**Comment by gehel** [comment]
> > I think we should put a circuit breaker on Server.execute(), which would prevent any work to go on a server that has problems.
> Anyway you need to wait timeout.
> For example you have timeout = 20 seconds and three nodes (one of them dead). During 20 seconds all threads in pool will be acquired by dead node.

Ideally, a circuit breaker should be much more aggressive, and proactive. But then the implementation starts to be more complex... I'm not quite ready yet to bring something like hystrix as a dependency.

So yes, having isolated thread pools seems like the right way to go...

**Comment by kipwoker** [comment]
@gehel 
I've described some things about executors. Check it out:
https://github.com/jmxtrans/jmxtrans/wiki/Configuration

**Comment by gehel** [comment]
@kipwoker looks great! Again, thanks a lot!
