### ISSUE TITLE
Support for grouping of multiple metrics into one result

### ISSUE THREAD

**Issue by allenmchan** [jmxtrans/jmxtrans#661]
It looks like the current design is to output a doc (or line depending on configured output) per metric.
I have a need to run calculations over metrics that the receiving system cannot execute if they are not the same document.

An example of the math (HeapMemoryUsage.used / HeapMemoryUsage.max) * 100 = heapPercentUsed. I have a bunch of other use cases similar to this.

Can you add an ability to configure jmxtrans to output all the metrics configured in a json configuratuon doc (I have one server per json config) as one object?

Something like this is what i require
"host": "server1",
"epoch": 1521236466535,
"Uptime": 46794092,
"DaemonThreadCount": 256,
"PeakThreadCount": 1464,
"OpenFileDescriptorCount": 702,
"ThreadCount": 1256,
"TotalStartedThreadCount": 19153,
"HeapMemoryUsage.committed": 5368709120,
"HeapMemoryUsage.init": 5368709120,
"HeapMemoryUsage.max": 5368709120,
"HeapMemoryUsage.used": 1947344656
}

If it is already possible, then i apologize. Please point me in the right direction as i already asked in the google groups and read through a ton of tickets.

**Comment by gehel** [comment]
Sadly, this isn't possible reliably. Each query is executed independently in jmxtrans. Some output writers buffer results and aggregate them, but this is done mainly for performance reasons. With the current design of jmxtrans, it would be non trivial to aggregate results reliably.

Feel free to dig into the code and submit a patch...

**Comment by allenmchan** [comment]
ok, closing this then.
