### ISSUE TITLE
jmxtrans only fetches and sends around every 15 minutes

### ISSUE THREAD

**Issue by dploeger** [jmxtrans/jmxtrans#687]
I expected the parameter "-s 60" to make jmxtrans fetch and send jmx data every minute. However, in my installation, it only does that every 15 minutes. 

I'm querying 19 hosts. Does "-s 60" mean, that every 60 seconds the next host is processed? If so, how can this process be paralelized?

**Comment by david-guenault** [comment]
hi, do you have an example configuration ?

**Comment by dploeger** [comment]
I guess, this has been fixed somewhere. Looking at the current configuration including "-s 60" it works as expected. Thanks
