### ISSUE TITLE
Jmxtrans stops working on some hours

### ISSUE THREAD

**Issue by abeyaert** [jmxtrans/jmxtrans#706]
Hello,

I currently make running JMXtrans to get metrics on a kafka broker, but for some reasons I don't figure out why, it stops working at some hours of the day since we tested this solution. Here is the typical message I get from the log file generated : 

`2018-09-26 00:00:40 [Thread-3] level com.googlecode.jmxtrans.JmxTransformer [JmxTransformer.java:548] - Configuration file deleted: /appl/TCE/jmxtrans/jmxtrans-20180925-1.log12649226750275758.tmp
2018-09-26 00:00:41 [Thread-3] level com.googlecode.jmxtrans.JmxTransformer [JmxTransformer.java:490] - Deleted scheduled job: kafka_ip:port-12597292182365135-5673216442 group: ServerJob
`  

It also happened at 18h, 9h... Is there a reason why it deletes this file after some time, and on specific hours ?

Thanks for your help!

**Comment by abeyaert** [comment]
Any update on this issue ?

**Comment by gquintana** [comment]
Quartz was removed.
Issued shouldn't occur anymore
