### ISSUE TITLE
"numQueryThreads" tuning

### ISSUE THREAD

**Issue by ofauchon** [jmxtrans/jmxtrans#782]
Hi all,

I'm running a local jmxtrans for collecting a tomcat server metrics (both are on the same server).
On my setup, jmxtrans may collects hundred of technical and application metrics and send them 
to Graphite (with GraphiteWriterFactory)

I have some questions regarding "numQueryThreads" parameter:

- Are there guidelines for numQueryThreads tuning ?
- In what situations numQueryThreads can be a bottleneck ?
- Can I monitor QueryThreads usage to choose the best value ?

Thanks for your help .

Olivier

**Comment by gquintana** [comment]
To be honest numQueryThreads is  unused in recent releases.

The most important settings are global settings 
* --query-processor-executor-pool-size query:  number of threads in pool
* --query-processor-executor-work-queue-capacity:  size of the wait queue
* --use-separate-executors: thread pool per server or global thread pool

JMXTrans has a SEDA architecture with 3 stages:
1. Stage 1: Scheduled executor: every run period seconds, JMX queries are pushed to Stage 2
2. Stage 2: Query executor: each query of each server is run in parallel using the query processor thread pool (see above). The query results are pushed in Stage 3
3. Stege 3: Result executor: results are sent to writer like you Graphite writer

**Comment by ofauchon** [comment]
Thanks for the detailed explaination !
