### ISSUE TITLE
Dependency versions out of date & with security issues

### ISSUE THREAD

**Issue by CharlieHesketh** [jmxtrans/jmxtrans#783]
I have been looking at the latest version of JMX-Trans and have noticed that some of the dependencies are out of date and they also have various security flaws.

Here is a summary of the patches that will address the CVEs included in the attached file: 

**org.yaml_snakeyaml** version 1.23 | _fixed in 1.26_
**com.fasterxml.jackson.core_jackson-databind** version 2.9.9.3 | _fixed in 2.10.0_
**com.google.guava_guava** version 19 | _fixed in 24.1.1_
**io.netty_netty-codec** version 4.1.12.Final | _fixed in 4.1.46_

[jmxtrans-security-scan.csv.zip](https://github.com/jmxtrans/jmxtrans/files/5502500/jmxtrans-security-scan.csv.zip)

**Comment by gquintana** [comment]
Jackson and Guava fixed in #787 #788 #789
