### ISSUE TITLE
jmxtrans-all.jar missing?

### ISSUE THREAD

**Issue by SpOOnman** [jmxtrans/jmxtrans#81]
I've cloned a repository and run ./jmxtrans.sh eample.json. I get "Error: Unable to access jarfile jmxtrans-all.jar". Is it missing in github repository?

**Comment by pranavrao1** [comment]
Could you elaborate more on what you mean by build jmxtrans before?

**Comment by gehel** [comment]
You need to run `mvn clean install` to compile and package JmxTrans (prerequisite: having [Maven](http://maven.apache.org/) installed).

**Comment by pranavrao1** [comment]
I have got jmxtrans working previously without mvn . Not sure why now it is misbehaving.

**Comment by gehel** [comment]
We are in the process of moving to a maven based build. It's a bit messy at the moment, but should work better soon. RPM are already built if you activate the `rpm` profile (`mvn clean install -Prpm`). There is a [pull request](https://github.com/jmxtrans/jmxtrans/pull/228) in the work to create DEB as well. Sorry for the inconvenience.

**Comment by pranavrao1** [comment]
This issue can also be caused if things are not run as root.
